package com.ample.mis.hibernate.bo;

// default package
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ActionBO generated by hbm2java
 */
public class ActionBO  implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 680590521700010539L;
	private Integer actnId;
	private String actnName;
	private int actnOrderConstnt;
	private boolean actnRowStatus;
	private byte[] actnImage;
	private String actnLn;
	private Set<ModActionBO> ModActions = new HashSet<ModActionBO>(0);

	public ActionBO() {
	}

	public ActionBO(String actnName, int actnOrderConstnt, boolean actnRowStatus,
			String actnLn) {
		this.actnName = actnName;
		this.actnOrderConstnt = actnOrderConstnt;
		this.actnRowStatus = actnRowStatus;
		this.actnLn = actnLn;
	}

	public ActionBO(String actnName, int actnOrderConstnt, boolean actnRowStatus,
			byte[] actnImage, String actnLn, Set<ModActionBO> ModActionBOs) {
		this.actnName = actnName;
		this.actnOrderConstnt = actnOrderConstnt;
		this.actnRowStatus = actnRowStatus;
		this.actnImage = actnImage;
		this.actnLn = actnLn;
		this.ModActions = ModActionBOs;
	}

	public Integer getActnId() {
		return actnId;
	}

	public void setActnId(Integer actnId) {
		this.actnId = actnId;
	}

	public String getActnName() {
		return actnName;
	}

	public void setActnName(String actnName) {
		this.actnName = actnName;
	}

	public int getActnOrderConstnt() {
		return actnOrderConstnt;
	}

	public void setActnOrderConstnt(int actnOrderConstnt) {
		this.actnOrderConstnt = actnOrderConstnt;
	}

	public boolean isActnRowStatus() {
		return actnRowStatus;
	}

	public void setActnRowStatus(boolean actnRowStatus) {
		this.actnRowStatus = actnRowStatus;
	}

	public byte[] getActnImage() {
		return actnImage;
	}

	public void setActnImage(byte[] actnImage) {
		this.actnImage = actnImage;
	}

	public String getActnLn() {
		return actnLn;
	}

	public void setActnLn(String actnLn) {
		this.actnLn = actnLn;
	}

	public Set<ModActionBO> getModActions() {
		return ModActions;
	}

	public void setModActions(Set<ModActionBO> modActions) {
		ModActions = modActions;
	}

	

}
