package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BalanceAsonBO generated by hbm2java
 */
public class BalanceAsonBO  implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6285289324987638267L;
	private Integer blasonId;
	private int blasonLevelIden;
	private int blasonLevelFkId;
	private int blasonIdenFlag;
	private Integer blasonObCount;
	private Double blasonObAmount;
	private Date blasonLastupdated;
	private Double blasonObInterest;
	private Integer blasonOb1to3;
	private Integer blasonOb3to6;
	private Integer blasonObGrt6;

	public BalanceAsonBO() {
	}

	public BalanceAsonBO(int blasonLevelIden, int blasonLevelFkId,
			int blasonIdenFlag) {
		this.blasonLevelIden = blasonLevelIden;
		this.blasonLevelFkId = blasonLevelFkId;
		this.blasonIdenFlag = blasonIdenFlag;
	}

	public BalanceAsonBO(int blasonLevelIden, int blasonLevelFkId,
			int blasonIdenFlag, Integer blasonObCount, Double blasonObAmount,
			Date blasonLastupdated, Double blasonObInterest,
			Integer blasonOb1to3, Integer blasonOb3to6, Integer blasonObGrt6) {
		this.blasonLevelIden = blasonLevelIden;
		this.blasonLevelFkId = blasonLevelFkId;
		this.blasonIdenFlag = blasonIdenFlag;
		this.blasonObCount = blasonObCount;
		this.blasonObAmount = blasonObAmount;
		this.blasonLastupdated = new Date(blasonLastupdated.getTime());
		this.blasonObInterest = blasonObInterest;
		this.blasonOb1to3 = blasonOb1to3;
		this.blasonOb3to6 = blasonOb3to6;
		this.blasonObGrt6 = blasonObGrt6;
	}

	public Integer getBlasonId() {
		return blasonId;
	}

	public void setBlasonId(Integer blasonId) {
		this.blasonId = blasonId;
	}

	public int getBlasonLevelIden() {
		return blasonLevelIden;
	}

	public void setBlasonLevelIden(int blasonLevelIden) {
		this.blasonLevelIden = blasonLevelIden;
	}

	public int getBlasonLevelFkId() {
		return blasonLevelFkId;
	}

	public void setBlasonLevelFkId(int blasonLevelFkId) {
		this.blasonLevelFkId = blasonLevelFkId;
	}

	public int getBlasonIdenFlag() {
		return blasonIdenFlag;
	}

	public void setBlasonIdenFlag(int blasonIdenFlag) {
		this.blasonIdenFlag = blasonIdenFlag;
	}

	public Integer getBlasonObCount() {
		return blasonObCount;
	}

	public void setBlasonObCount(Integer blasonObCount) {
		this.blasonObCount = blasonObCount;
	}

	public Double getBlasonObAmount() {
		return blasonObAmount;
	}

	public void setBlasonObAmount(Double blasonObAmount) {
		this.blasonObAmount = blasonObAmount;
	}

	public Date getBlasonLastupdated() {
		return new Date(blasonLastupdated.getTime());
	}

	public void setBlasonLastupdated(Date blasonLastupdated) {
		this.blasonLastupdated = new Date(blasonLastupdated.getTime());
	}

	public Double getBlasonObInterest() {
		return blasonObInterest;
	}

	public void setBlasonObInterest(Double blasonObInterest) {
		this.blasonObInterest = blasonObInterest;
	}

	public Integer getBlasonOb1to3() {
		return blasonOb1to3;
	}

	public void setBlasonOb1to3(Integer blasonOb1to3) {
		this.blasonOb1to3 = blasonOb1to3;
	}

	public Integer getBlasonOb3to6() {
		return blasonOb3to6;
	}

	public void setBlasonOb3to6(Integer blasonOb3to6) {
		this.blasonOb3to6 = blasonOb3to6;
	}

	public Integer getBlasonObGrt6() {
		return blasonObGrt6;
	}

	public void setBlasonObGrt6(Integer blasonObGrt6) {
		this.blasonObGrt6 = blasonObGrt6;
	}

	

}
