package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CapacityBO generated by hbm2java
 */
public class CapacityBO implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5633239249493094141L;
	private Integer cptyId;
	private String cptyName;
	private boolean cptyRowStatus;
	private Set<TransformerBO> transformers = new HashSet<TransformerBO>(0);

	public CapacityBO() {
	}

	public CapacityBO(String cptyName, boolean cptyRowStatus) {
		this.cptyName = cptyName;
		this.cptyRowStatus = cptyRowStatus;
	}

	public CapacityBO(String cptyName, boolean cptyRowStatus,
			Set<TransformerBO> TransformerBOs) {
		this.cptyName = cptyName;
		this.cptyRowStatus = cptyRowStatus;
		this.transformers = TransformerBOs;
	}

	public Integer getCptyId() {
		return cptyId;
	}

	public void setCptyId(Integer cptyId) {
		this.cptyId = cptyId;
	}

	public String getCptyName() {
		return cptyName;
	}

	public void setCptyName(String cptyName) {
		this.cptyName = cptyName;
	}

	public boolean isCptyRowStatus() {
		return cptyRowStatus;
	}

	public void setCptyRowStatus(boolean cptyRowStatus) {
		this.cptyRowStatus = cptyRowStatus;
	}

	public Set<TransformerBO> getTransformers() {
		return transformers;
	}

	public void setTransformers(Set<TransformerBO> transformers) {
		this.transformers = transformers;
	}

	

}
