package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CasteCategoryBO generated by hbm2java
 */
public class CasteCategoryBO  implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4847869464943188065L;
	private Integer cstctgId;
	private String cstctgName;
	private boolean cstctgRowStatus;
	private String cstctgAka;
	private Set<ProgramWorksBO> ProgramWorkses = new HashSet<ProgramWorksBO>(0);

	public CasteCategoryBO() {
	}

	public CasteCategoryBO(String cstctgName, boolean cstctgRowStatus) {
		this.cstctgName = cstctgName;
		this.cstctgRowStatus = cstctgRowStatus;
	}

	public CasteCategoryBO(String cstctgName, boolean cstctgRowStatus,
			String cstctgAka, Set<ProgramWorksBO> ProgramWorksBOes) {
		this.cstctgName = cstctgName;
		this.cstctgRowStatus = cstctgRowStatus;
		this.cstctgAka = cstctgAka;
		this.ProgramWorkses = ProgramWorksBOes;
	}

	public Integer getCstctgId() {
		return cstctgId;
	}

	public void setCstctgId(Integer cstctgId) {
		this.cstctgId = cstctgId;
	}

	public String getCstctgName() {
		return cstctgName;
	}

	public void setCstctgName(String cstctgName) {
		this.cstctgName = cstctgName;
	}

	public boolean isCstctgRowStatus() {
		return cstctgRowStatus;
	}

	public void setCstctgRowStatus(boolean cstctgRowStatus) {
		this.cstctgRowStatus = cstctgRowStatus;
	}

	public String getCstctgAka() {
		return cstctgAka;
	}

	public void setCstctgAka(String cstctgAka) {
		this.cstctgAka = cstctgAka;
	}

	public Set<ProgramWorksBO> getProgramWorkses() {
		return ProgramWorkses;
	}

	public void setProgramWorkses(Set<ProgramWorksBO> programWorkses) {
		ProgramWorkses = programWorkses;
	}

	

	
	

}
