package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CircleBO generated by hbm2java
 */
public class CircleBO  implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1782871999351972785L;
	private Integer crclId;
	private ZoneBO Zone;
	private String crclShortCode;
	private String crclName;
	private Date crclFromDate;
	private Date crclToDate;
	private boolean crclRowStatus;
	private Long crclCreatedBy;
	private Date crclCreatedDate;
	private Long crclLastUpdatedBy;
	private Date crclLastUpdatedDate;
	private Set<DivisionBO> Divisions = new HashSet<DivisionBO>(0);

	public CircleBO() {
	}

	public CircleBO(ZoneBO ZoneBO, String crclShortCode, String crclName,
			Date crclFromDate, boolean crclRowStatus) {
		this.Zone = ZoneBO;
		this.crclShortCode = crclShortCode;
		this.crclName = crclName;
		this.crclFromDate = crclFromDate;
		this.crclRowStatus = crclRowStatus;
	}

	public CircleBO(ZoneBO ZoneBO, String crclShortCode, String crclName,
			Date crclFromDate, Date crclToDate, boolean crclRowStatus,
			Long crclCreatedBy, Date crclCreatedDate, Long crclLastUpdatedBy,
			Date crclLastUpdatedDate, Set<DivisionBO> DivisionBOs) {
		this.Zone = ZoneBO;
		this.crclShortCode = crclShortCode;
		this.crclName = crclName;
		this.crclFromDate = crclFromDate;
		this.crclToDate = crclToDate;
		this.crclRowStatus = crclRowStatus;
		this.crclCreatedBy = crclCreatedBy;
		this.crclCreatedDate = crclCreatedDate;
		this.crclLastUpdatedBy = crclLastUpdatedBy;
		this.crclLastUpdatedDate = crclLastUpdatedDate;
		this.Divisions = DivisionBOs;
	}

	public Integer getCrclId() {
		return crclId;
	}

	public void setCrclId(Integer crclId) {
		this.crclId = crclId;
	}

	public ZoneBO getZone() {
		return Zone;
	}

	public void setZone(ZoneBO zone) {
		Zone = zone;
	}

	public String getCrclShortCode() {
		return crclShortCode;
	}

	public void setCrclShortCode(String crclShortCode) {
		this.crclShortCode = crclShortCode;
	}

	public String getCrclName() {
		return crclName;
	}

	public void setCrclName(String crclName) {
		this.crclName = crclName;
	}

	public Date getCrclFromDate() {
		return crclFromDate;
	}

	public void setCrclFromDate(Date crclFromDate) {
		this.crclFromDate = crclFromDate;
	}

	public Date getCrclToDate() {
		return crclToDate;
	}

	public void setCrclToDate(Date crclToDate) {
		this.crclToDate = crclToDate;
	}

	public boolean isCrclRowStatus() {
		return crclRowStatus;
	}

	public void setCrclRowStatus(boolean crclRowStatus) {
		this.crclRowStatus = crclRowStatus;
	}

	public Long getCrclCreatedBy() {
		return crclCreatedBy;
	}

	public void setCrclCreatedBy(Long crclCreatedBy) {
		this.crclCreatedBy = crclCreatedBy;
	}

	public Date getCrclCreatedDate() {
		return crclCreatedDate;
	}

	public void setCrclCreatedDate(Date crclCreatedDate) {
		this.crclCreatedDate = crclCreatedDate;
	}

	public Long getCrclLastUpdatedBy() {
		return crclLastUpdatedBy;
	}

	public void setCrclLastUpdatedBy(Long crclLastUpdatedBy) {
		this.crclLastUpdatedBy = crclLastUpdatedBy;
	}

	public Date getCrclLastUpdatedDate() {
		return crclLastUpdatedDate;
	}

	public void setCrclLastUpdatedDate(Date crclLastUpdatedDate) {
		this.crclLastUpdatedDate = crclLastUpdatedDate;
	}

	public Set<DivisionBO> getDivisions() {
		return Divisions;
	}

	public void setDivisions(Set<DivisionBO> divisions) {
		Divisions = divisions;
	}

	

}
