package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ConstituencyBO generated by hbm2java
 */
public class ConstituencyBO  implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6555713362235233597L;
	private Integer constyId;
	private SectionBO Section;
	private String constyShortCode;
	private String constyName;
	private Date constyFromDate;
	private Date constyToDate;
	private boolean constyRowStatus;
	private Long constyCreatedBy;
	private Date constyCreatedDate;
	private Long constyLastUpdatedBy;
	private Date constyLastUpdatedDate;

	public ConstituencyBO() {
	}

	public ConstituencyBO(SectionBO SectionBO, String constyShortCode,
			String constyName, Date constyFromDate, boolean constyRowStatus) {
		this.Section = SectionBO;
		this.constyShortCode = constyShortCode;
		this.constyName = constyName;
		this.constyFromDate = constyFromDate;
		this.constyRowStatus = constyRowStatus;
	}

	public ConstituencyBO(SectionBO SectionBO, String constyShortCode,
			String constyName, Date constyFromDate, Date constyToDate,
			boolean constyRowStatus, Long constyCreatedBy,
			Date constyCreatedDate, Long constyLastUpdatedBy,
			Date constyLastUpdatedDate) {
		this.Section = SectionBO;
		this.constyShortCode = constyShortCode;
		this.constyName = constyName;
		this.constyFromDate = constyFromDate;
		this.constyToDate = constyToDate;
		this.constyRowStatus = constyRowStatus;
		this.constyCreatedBy = constyCreatedBy;
		this.constyCreatedDate = constyCreatedDate;
		this.constyLastUpdatedBy = constyLastUpdatedBy;
		this.constyLastUpdatedDate = constyLastUpdatedDate;
	}

	public Integer getConstyId() {
		return constyId;
	}

	public void setConstyId(Integer constyId) {
		this.constyId = constyId;
	}

	public SectionBO getSection() {
		return Section;
	}

	public void setSection(SectionBO section) {
		Section = section;
	}

	public String getConstyShortCode() {
		return constyShortCode;
	}

	public void setConstyShortCode(String constyShortCode) {
		this.constyShortCode = constyShortCode;
	}

	public String getConstyName() {
		return constyName;
	}

	public void setConstyName(String constyName) {
		this.constyName = constyName;
	}

	public Date getConstyFromDate() {
		return constyFromDate;
	}

	public void setConstyFromDate(Date constyFromDate) {
		this.constyFromDate = constyFromDate;
	}

	public Date getConstyToDate() {
		return constyToDate;
	}

	public void setConstyToDate(Date constyToDate) {
		this.constyToDate = constyToDate;
	}

	public boolean isConstyRowStatus() {
		return constyRowStatus;
	}

	public void setConstyRowStatus(boolean constyRowStatus) {
		this.constyRowStatus = constyRowStatus;
	}

	public Long getConstyCreatedBy() {
		return constyCreatedBy;
	}

	public void setConstyCreatedBy(Long constyCreatedBy) {
		this.constyCreatedBy = constyCreatedBy;
	}

	public Date getConstyCreatedDate() {
		return constyCreatedDate;
	}

	public void setConstyCreatedDate(Date constyCreatedDate) {
		this.constyCreatedDate = constyCreatedDate;
	}

	public Long getConstyLastUpdatedBy() {
		return constyLastUpdatedBy;
	}

	public void setConstyLastUpdatedBy(Long constyLastUpdatedBy) {
		this.constyLastUpdatedBy = constyLastUpdatedBy;
	}

	public Date getConstyLastUpdatedDate() {
		return constyLastUpdatedDate;
	}

	public void setConstyLastUpdatedDate(Date constyLastUpdatedDate) {
		this.constyLastUpdatedDate = constyLastUpdatedDate;
	}

	

	

}
