package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Deposit generated by hbm2java
 */
public class DepositBO  implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8177420385610513203L;
	private Integer depstId;
	private String depstName;
	private boolean depstRowStatus;
	private Set<ProgramDepositBO> programDeposits = new HashSet<ProgramDepositBO>(0);

	public DepositBO() {
	}

	public DepositBO(String depstName, boolean depstRowStatus) {
		this.depstName = depstName;
		this.depstRowStatus = depstRowStatus;
	}

	public DepositBO(String depstName, boolean depstRowStatus,
			Set<ProgramDepositBO> programDeposits) {
		this.depstName = depstName;
		this.depstRowStatus = depstRowStatus;
		this.programDeposits = programDeposits;
	}

	public Integer getDepstId() {
		return depstId;
	}

	public void setDepstId(Integer depstId) {
		this.depstId = depstId;
	}

	public String getDepstName() {
		return depstName;
	}

	public void setDepstName(String depstName) {
		this.depstName = depstName;
	}

	public boolean isDepstRowStatus() {
		return depstRowStatus;
	}

	public void setDepstRowStatus(boolean depstRowStatus) {
		this.depstRowStatus = depstRowStatus;
	}

	public Set<ProgramDepositBO> getProgramDeposits() {
		return programDeposits;
	}

	public void setProgramDeposits(Set<ProgramDepositBO> programDeposits) {
		this.programDeposits = programDeposits;
	}

	

}
