package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Designation generated by hbm2java
 */
public class DesignationBO  implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer desgId;
	private String desgShortCode;
	private String desgName;
	private Date desgFromDate;
	private Date desgToDate;
	private boolean desgRowStatus;
	private Long desgCreatedBy;
	private Date desgCreatedDate;
	private Long desgLastUpdatedBy;
	private Date desgLastUpdatedDate;
	private Set<EmployeeBO> employees = new HashSet<EmployeeBO>(0);

	public DesignationBO() {
	}

	public DesignationBO(String desgShortCode, String desgName,
			Date desgFromDate, boolean desgRowStatus) {
		this.desgShortCode = desgShortCode;
		this.desgName = desgName;
		this.desgFromDate = desgFromDate;
		this.desgRowStatus = desgRowStatus;
	}

	public DesignationBO(String desgShortCode, String desgName,
			Date desgFromDate, Date desgToDate, boolean desgRowStatus,
			Long desgCreatedBy, Date desgCreatedDate, Long desgLastUpdatedBy,
			Date desgLastUpdatedDate, Set<EmployeeBO> employees) {
		this.desgShortCode = desgShortCode;
		this.desgName = desgName;
		this.desgFromDate = desgFromDate;
		this.desgToDate = desgToDate;
		this.desgRowStatus = desgRowStatus;
		this.desgCreatedBy = desgCreatedBy;
		this.desgCreatedDate = desgCreatedDate;
		this.desgLastUpdatedBy = desgLastUpdatedBy;
		this.desgLastUpdatedDate = desgLastUpdatedDate;
		this.employees = employees;
	}

	public Integer getDesgId() {
		return this.desgId;
	}

	public void setDesgId(Integer desgId) {
		this.desgId = desgId;
	}

	public String getDesgShortCode() {
		return this.desgShortCode;
	}

	public void setDesgShortCode(String desgShortCode) {
		this.desgShortCode = desgShortCode;
	}

	public String getDesgName() {
		return this.desgName;
	}

	public void setDesgName(String desgName) {
		this.desgName = desgName;
	}

	public Date getDesgFromDate() {
		return this.desgFromDate;
	}

	public void setDesgFromDate(Date desgFromDate) {
		this.desgFromDate = desgFromDate;
	}

	public Date getDesgToDate() {
		return this.desgToDate;
	}

	public void setDesgToDate(Date desgToDate) {
		this.desgToDate = desgToDate;
	}

	public boolean isDesgRowStatus() {
		return this.desgRowStatus;
	}

	public void setDesgRowStatus(boolean desgRowStatus) {
		this.desgRowStatus = desgRowStatus;
	}

	public Long getDesgCreatedBy() {
		return this.desgCreatedBy;
	}

	public void setDesgCreatedBy(Long desgCreatedBy) {
		this.desgCreatedBy = desgCreatedBy;
	}

	public Date getDesgCreatedDate() {
		return this.desgCreatedDate;
	}

	public void setDesgCreatedDate(Date desgCreatedDate) {
		this.desgCreatedDate = desgCreatedDate;
	}

	public Long getDesgLastUpdatedBy() {
		return this.desgLastUpdatedBy;
	}

	public void setDesgLastUpdatedBy(Long desgLastUpdatedBy) {
		this.desgLastUpdatedBy = desgLastUpdatedBy;
	}

	public Date getDesgLastUpdatedDate() {
		return this.desgLastUpdatedDate;
	}

	public void setDesgLastUpdatedDate(Date desgLastUpdatedDate) {
		this.desgLastUpdatedDate = desgLastUpdatedDate;
	}

	public Set<EmployeeBO> getEmployees() {
		return employees;
	}

	public void setEmployees(Set<EmployeeBO> employees) {
		this.employees = employees;
	}


}
