package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Discrepancy generated by hbm2java
 */
public class DiscrepancyBO  implements  java.io.Serializable {

	private Integer dcrepId;
	private String dcrepName;
	private boolean dcrepRowStatus;
	private Set<DiscrepancyDetailBO> discrepancyDetails = new HashSet<DiscrepancyDetailBO>(
			0);

	public DiscrepancyBO() {
	}

	public DiscrepancyBO(String dcrepName, boolean dcrepRowStatus) {
		this.dcrepName = dcrepName;
		this.dcrepRowStatus = dcrepRowStatus;
	}

	public DiscrepancyBO(String dcrepName, boolean dcrepRowStatus,
			Set<DiscrepancyDetailBO> discrepancyDetails) {
		this.dcrepName = dcrepName;
		this.dcrepRowStatus = dcrepRowStatus;
		this.discrepancyDetails = discrepancyDetails;
	}

	public Integer getDcrepId() {
		return this.dcrepId;
	}

	public void setDcrepId(Integer dcrepId) {
		this.dcrepId = dcrepId;
	}

	public String getDcrepName() {
		return this.dcrepName;
	}

	public void setDcrepName(String dcrepName) {
		this.dcrepName = dcrepName;
	}

	public boolean isDcrepRowStatus() {
		return this.dcrepRowStatus;
	}

	public void setDcrepRowStatus(boolean dcrepRowStatus) {
		this.dcrepRowStatus = dcrepRowStatus;
	}

	public Set<DiscrepancyDetailBO> getDiscrepancyDetails() {
		return this.discrepancyDetails;
	}

	public void setDiscrepancyDetails(Set<DiscrepancyDetailBO> discrepancyDetails) {
		this.discrepancyDetails = discrepancyDetails;
	}

}
