package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * Disconnection generated by hbm2java
 */
public class DisconnectionBO  implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long discId;
	private TranHeadBO tranHead;
	private Integer discVisited;
	private Integer discDisconnect;
	private Integer discReconnect;
	private Double discAmntInvolve;
	private Double discAmntRealise;
	private Integer discCntob;
	private Integer discCntcb;
	private Double discAmntob;
	private Double discAmountcb;
	private String discRemarks;

	public DisconnectionBO() {
	}

	public DisconnectionBO(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public DisconnectionBO(TranHeadBO tranHead, Integer discVisited,
			Integer discDisconnect, Integer discReconnect,
			Double discAmntInvolve, Double discAmntRealise, Integer discCntob,
			Integer discCntcb, Double discAmntob, Double discAmountcb,
			String discRemarks) {
		this.tranHead = tranHead;
		this.discVisited = discVisited;
		this.discDisconnect = discDisconnect;
		this.discReconnect = discReconnect;
		this.discAmntInvolve = discAmntInvolve;
		this.discAmntRealise = discAmntRealise;
		this.discCntob = discCntob;
		this.discCntcb = discCntcb;
		this.discAmntob = discAmntob;
		this.discAmountcb = discAmountcb;
		this.discRemarks = discRemarks;
	}

	public Long getDiscId() {
		return this.discId;
	}

	public void setDiscId(Long discId) {
		this.discId = discId;
	}

	public TranHeadBO getTranHead() {
		return this.tranHead;
	}

	public void setTranHead(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public Integer getDiscVisited() {
		return this.discVisited;
	}

	public void setDiscVisited(Integer discVisited) {
		this.discVisited = discVisited;
	}

	public Integer getDiscDisconnect() {
		return this.discDisconnect;
	}

	public void setDiscDisconnect(Integer discDisconnect) {
		this.discDisconnect = discDisconnect;
	}

	public Integer getDiscReconnect() {
		return this.discReconnect;
	}

	public void setDiscReconnect(Integer discReconnect) {
		this.discReconnect = discReconnect;
	}

	public Double getDiscAmntInvolve() {
		return this.discAmntInvolve;
	}

	public void setDiscAmntInvolve(Double discAmntInvolve) {
		this.discAmntInvolve = discAmntInvolve;
	}

	public Double getDiscAmntRealise() {
		return this.discAmntRealise;
	}

	public void setDiscAmntRealise(Double discAmntRealise) {
		this.discAmntRealise = discAmntRealise;
	}

	public Integer getDiscCntob() {
		return this.discCntob;
	}

	public void setDiscCntob(Integer discCntob) {
		this.discCntob = discCntob;
	}

	public Integer getDiscCntcb() {
		return this.discCntcb;
	}

	public void setDiscCntcb(Integer discCntcb) {
		this.discCntcb = discCntcb;
	}

	public Double getDiscAmntob() {
		return this.discAmntob;
	}

	public void setDiscAmntob(Double discAmntob) {
		this.discAmntob = discAmntob;
	}

	public Double getDiscAmountcb() {
		return this.discAmountcb;
	}

	public void setDiscAmountcb(Double discAmountcb) {
		this.discAmountcb = discAmountcb;
	}

	public String getDiscRemarks() {
		return this.discRemarks;
	}

	public void setDiscRemarks(String discRemarks) {
		this.discRemarks = discRemarks;
	}

}
