package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * Doorlock generated by hbm2java
 */
public class DoorlockBO  implements  java.io.Serializable {

	private Long drlckId;
	private TranHeadBO tranHead;
	private Integer drlckNoofInstance;
	private Integer drlckShiftOb;
	private Integer drlckNoofNotice;
	private Integer drlckNoofShifted;
	private Integer drlckNotShifted;
	private Integer drlckCb;
	private String drlckReason;
	private boolean drlckRowStatus;
	private Integer drlckIdenFlag;

	public DoorlockBO() {
	}

	public DoorlockBO(TranHeadBO tranHead, boolean drlckRowStatus) {
		this.tranHead = tranHead;
		this.drlckRowStatus = drlckRowStatus;
	}

	public DoorlockBO(TranHeadBO tranHead, Integer drlckNoofInstance,
			Integer drlckShiftOb, Integer drlckNoofNotice,
			Integer drlckNoofShifted, Integer drlckNotShifted, Integer drlckCb,
			String drlckReason, boolean drlckRowStatus, Integer drlckIdenFlag) {
		this.tranHead = tranHead;
		this.drlckNoofInstance = drlckNoofInstance;
		this.drlckShiftOb = drlckShiftOb;
		this.drlckNoofNotice = drlckNoofNotice;
		this.drlckNoofShifted = drlckNoofShifted;
		this.drlckNotShifted = drlckNotShifted;
		this.drlckCb = drlckCb;
		this.drlckReason = drlckReason;
		this.drlckRowStatus = drlckRowStatus;
		this.drlckIdenFlag = drlckIdenFlag;
	}

	public Long getDrlckId() {
		return this.drlckId;
	}

	public void setDrlckId(Long drlckId) {
		this.drlckId = drlckId;
	}

	public TranHeadBO getTranHead() {
		return this.tranHead;
	}

	public void setTranHead(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public Integer getDrlckNoofInstance() {
		return this.drlckNoofInstance;
	}

	public void setDrlckNoofInstance(Integer drlckNoofInstance) {
		this.drlckNoofInstance = drlckNoofInstance;
	}

	public Integer getDrlckShiftOb() {
		return this.drlckShiftOb;
	}

	public void setDrlckShiftOb(Integer drlckShiftOb) {
		this.drlckShiftOb = drlckShiftOb;
	}

	public Integer getDrlckNoofNotice() {
		return this.drlckNoofNotice;
	}

	public void setDrlckNoofNotice(Integer drlckNoofNotice) {
		this.drlckNoofNotice = drlckNoofNotice;
	}

	public Integer getDrlckNoofShifted() {
		return this.drlckNoofShifted;
	}

	public void setDrlckNoofShifted(Integer drlckNoofShifted) {
		this.drlckNoofShifted = drlckNoofShifted;
	}

	public Integer getDrlckNotShifted() {
		return this.drlckNotShifted;
	}

	public void setDrlckNotShifted(Integer drlckNotShifted) {
		this.drlckNotShifted = drlckNotShifted;
	}

	public Integer getDrlckCb() {
		return this.drlckCb;
	}

	public void setDrlckCb(Integer drlckCb) {
		this.drlckCb = drlckCb;
	}

	public String getDrlckReason() {
		return this.drlckReason;
	}

	public void setDrlckReason(String drlckReason) {
		this.drlckReason = drlckReason;
	}

	public boolean isDrlckRowStatus() {
		return this.drlckRowStatus;
	}

	public void setDrlckRowStatus(boolean drlckRowStatus) {
		this.drlckRowStatus = drlckRowStatus;
	}

	public Integer getDrlckIdenFlag() {
		return this.drlckIdenFlag;
	}

	public void setDrlckIdenFlag(Integer drlckIdenFlag) {
		this.drlckIdenFlag = drlckIdenFlag;
	}

}
