package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class EmployeeBO  implements  java.io.Serializable {

	private Long empId;
	private DesignationBO designation;
	private DepartmentBO department;
	private String empCode;
	private String empName;
	private boolean empRowStatus;
	private Set<UsersBO> userses = new HashSet<UsersBO>(0);

	public EmployeeBO() {
	}

	public EmployeeBO(String empCode, String empName, boolean empRowStatus) {
		this.empCode = empCode;
		this.empName = empName;
		this.empRowStatus = empRowStatus;
	}

	public EmployeeBO(DesignationBO designation, DepartmentBO department,
			String empCode, String empName, boolean empRowStatus,
			Set<UsersBO> userses) {
		this.designation = designation;
		this.department = department;
		this.empCode = empCode;
		this.empName = empName;
		this.empRowStatus = empRowStatus;
		this.userses = userses;
	}

	public Long getEmpId() {
		return this.empId;
	}

	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	public DesignationBO getDesignation() {
		return this.designation;
	}

	public void setDesignation(DesignationBO designation) {
		this.designation = designation;
	}

	public DepartmentBO getDepartment() {
		return this.department;
	}

	public void setDepartment(DepartmentBO department) {
		this.department = department;
	}

	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public boolean isEmpRowStatus() {
		return this.empRowStatus;
	}

	public void setEmpRowStatus(boolean empRowStatus) {
		this.empRowStatus = empRowStatus;
	}

	public Set<UsersBO> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<UsersBO> userses) {
		this.userses = userses;
	}

}
