package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Feeder generated by hbm2java
 */
public class FeederBO  implements  java.io.Serializable {

	private Integer fdrId;
	private String fdrName;
	private boolean fdrRowStatus;
	private Set<FeederLineBO> feederLines = new HashSet<FeederLineBO>(0);

	public FeederBO() {
	}

	public FeederBO(String fdrName, boolean fdrRowStatus) {
		this.fdrName = fdrName;
		this.fdrRowStatus = fdrRowStatus;
	}

	public FeederBO(String fdrName, boolean fdrRowStatus,
			Set<FeederLineBO> feederLines) {
		this.fdrName = fdrName;
		this.fdrRowStatus = fdrRowStatus;
		this.feederLines = feederLines;
	}

	public Integer getFdrId() {
		return this.fdrId;
	}

	public void setFdrId(Integer fdrId) {
		this.fdrId = fdrId;
	}

	public String getFdrName() {
		return this.fdrName;
	}

	public void setFdrName(String fdrName) {
		this.fdrName = fdrName;
	}

	public boolean isFdrRowStatus() {
		return this.fdrRowStatus;
	}

	public void setFdrRowStatus(boolean fdrRowStatus) {
		this.fdrRowStatus = fdrRowStatus;
	}

	public Set<FeederLineBO> getFeederLines() {
		return this.feederLines;
	}

	public void setFeederLines(Set<FeederLineBO> feederLines) {
		this.feederLines = feederLines;
	}

}
