package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * FeederLine generated by hbm2java
 */
public class FeederLineBO  implements  java.io.Serializable {

	private Long flId;
	private TranHeadBO tranHead;
	private FeederBO feeder;
	private Integer flFdrTrippedCount;
	private String flFdrReason;
	private boolean flRowStatus;

	public FeederLineBO() {
	}

	public FeederLineBO(TranHeadBO tranHead, FeederBO feeder, boolean flRowStatus) {
		this.tranHead = tranHead;
		this.feeder = feeder;
		this.flRowStatus = flRowStatus;
	}

	public FeederLineBO(TranHeadBO tranHead, FeederBO feeder,
			Integer flFdrTrippedCount, String flFdrReason, boolean flRowStatus) {
		this.tranHead = tranHead;
		this.feeder = feeder;
		this.flFdrTrippedCount = flFdrTrippedCount;
		this.flFdrReason = flFdrReason;
		this.flRowStatus = flRowStatus;
	}

	public Long getFlId() {
		return this.flId;
	}

	public void setFlId(Long flId) {
		this.flId = flId;
	}

	public TranHeadBO getTranHead() {
		return this.tranHead;
	}

	public void setTranHead(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public FeederBO getFeeder() {
		return this.feeder;
	}

	public void setFeeder(FeederBO feeder) {
		this.feeder = feeder;
	}

	public Integer getFlFdrTrippedCount() {
		return this.flFdrTrippedCount;
	}

	public void setFlFdrTrippedCount(Integer flFdrTrippedCount) {
		this.flFdrTrippedCount = flFdrTrippedCount;
	}

	public String getFlFdrReason() {
		return this.flFdrReason;
	}

	public void setFlFdrReason(String flFdrReason) {
		this.flFdrReason = flFdrReason;
	}

	public boolean isFlRowStatus() {
		return this.flRowStatus;
	}

	public void setFlRowStatus(boolean flRowStatus) {
		this.flRowStatus = flRowStatus;
	}

}
