package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * Instalation generated by hbm2java
 */
public class InstalationBO  implements  java.io.Serializable {

	private Long instlId;
	private TranHeadBO tranHead;
	private int instlIdenFlag;
	private Double instlPrincipal;
	private Double instlInterest;
	private boolean instlRowStatus;

	public InstalationBO() {
	}

	public InstalationBO(TranHeadBO tranHead, int instlIdenFlag,
			boolean instlRowStatus) {
		this.tranHead = tranHead;
		this.instlIdenFlag = instlIdenFlag;
		this.instlRowStatus = instlRowStatus;
	}

	public InstalationBO(TranHeadBO tranHead, int instlIdenFlag,
			Double instlPrincipal, Double instlInterest, boolean instlRowStatus) {
		this.tranHead = tranHead;
		this.instlIdenFlag = instlIdenFlag;
		this.instlPrincipal = instlPrincipal;
		this.instlInterest = instlInterest;
		this.instlRowStatus = instlRowStatus;
	}

	public Long getInstlId() {
		return this.instlId;
	}

	public void setInstlId(Long instlId) {
		this.instlId = instlId;
	}

	public TranHeadBO getTranHead() {
		return this.tranHead;
	}

	public void setTranHead(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public int getInstlIdenFlag() {
		return this.instlIdenFlag;
	}

	public void setInstlIdenFlag(int instlIdenFlag) {
		this.instlIdenFlag = instlIdenFlag;
	}

	public Double getInstlPrincipal() {
		return this.instlPrincipal;
	}

	public void setInstlPrincipal(Double instlPrincipal) {
		this.instlPrincipal = instlPrincipal;
	}

	public Double getInstlInterest() {
		return this.instlInterest;
	}

	public void setInstlInterest(Double instlInterest) {
		this.instlInterest = instlInterest;
	}

	public boolean isInstlRowStatus() {
		return this.instlRowStatus;
	}

	public void setInstlRowStatus(boolean instlRowStatus) {
		this.instlRowStatus = instlRowStatus;
	}

}
