package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * MnrDetail generated by hbm2java
 */
public class MnrDetailBO  implements  java.io.Serializable {

	private Long mdetId;
	private TranHeadBO tranHead;
	private Integer mdetIdenFlag;
	private Integer mdetOb;
	private Integer mdetInstalation;
	private Integer mdetReplaced;
	private Integer mdetCb;
	private boolean mdetRowStatus;

	public MnrDetailBO() {
	}

	public MnrDetailBO(TranHeadBO tranHead, boolean mdetRowStatus) {
		this.tranHead = tranHead;
		this.mdetRowStatus = mdetRowStatus;
	}

	public MnrDetailBO(TranHeadBO tranHead, Integer mdetIdenFlag, Integer mdetOb,
			Integer mdetInstalation, Integer mdetReplaced, Integer mdetCb,
			boolean mdetRowStatus) {
		this.tranHead = tranHead;
		this.mdetIdenFlag = mdetIdenFlag;
		this.mdetOb = mdetOb;
		this.mdetInstalation = mdetInstalation;
		this.mdetReplaced = mdetReplaced;
		this.mdetCb = mdetCb;
		this.mdetRowStatus = mdetRowStatus;
	}

	public Long getMdetId() {
		return this.mdetId;
	}

	public void setMdetId(Long mdetId) {
		this.mdetId = mdetId;
	}

	public TranHeadBO getTranHead() {
		return this.tranHead;
	}

	public void setTranHead(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public Integer getMdetIdenFlag() {
		return this.mdetIdenFlag;
	}

	public void setMdetIdenFlag(Integer mdetIdenFlag) {
		this.mdetIdenFlag = mdetIdenFlag;
	}

	public Integer getMdetOb() {
		return this.mdetOb;
	}

	public void setMdetOb(Integer mdetOb) {
		this.mdetOb = mdetOb;
	}

	public Integer getMdetInstalation() {
		return this.mdetInstalation;
	}

	public void setMdetInstalation(Integer mdetInstalation) {
		this.mdetInstalation = mdetInstalation;
	}

	public Integer getMdetReplaced() {
		return this.mdetReplaced;
	}

	public void setMdetReplaced(Integer mdetReplaced) {
		this.mdetReplaced = mdetReplaced;
	}

	public Integer getMdetCb() {
		return this.mdetCb;
	}

	public void setMdetCb(Integer mdetCb) {
		this.mdetCb = mdetCb;
	}

	public boolean isMdetRowStatus() {
		return this.mdetRowStatus;
	}

	public void setMdetRowStatus(boolean mdetRowStatus) {
		this.mdetRowStatus = mdetRowStatus;
	}

}
