package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ModAction generated by hbm2java
 */
public class ModActionBO  implements  java.io.Serializable {

	private Integer macnId;
	private ActionBO action;
	private ModuleBO module;
	private boolean macnRowStatus;
	private boolean macnIden;
	private Set<RolModActionBO> rolModActions = new HashSet<RolModActionBO>(0);

	public ModActionBO() {
	}

	public ModActionBO(ActionBO action, ModuleBO module, boolean macnRowStatus,
			boolean macnIden) {
		this.action = action;
		this.module = module;
		this.macnRowStatus = macnRowStatus;
		this.macnIden = macnIden;
	}

	public ModActionBO(ActionBO action, ModuleBO module, boolean macnRowStatus,
			boolean macnIden, Set<RolModActionBO> rolModActions) {
		this.action = action;
		this.module = module;
		this.macnRowStatus = macnRowStatus;
		this.macnIden = macnIden;
		this.rolModActions = rolModActions;
	}

	public Integer getMacnId() {
		return this.macnId;
	}

	public void setMacnId(Integer macnId) {
		this.macnId = macnId;
	}

	public ActionBO getAction() {
		return this.action;
	}

	public void setAction(ActionBO action) {
		this.action = action;
	}

	public ModuleBO getModule() {
		return this.module;
	}

	public void setModule(ModuleBO module) {
		this.module = module;
	}

	public boolean isMacnRowStatus() {
		return this.macnRowStatus;
	}

	public void setMacnRowStatus(boolean macnRowStatus) {
		this.macnRowStatus = macnRowStatus;
	}

	public boolean isMacnIden() {
		return this.macnIden;
	}

	public void setMacnIden(boolean macnIden) {
		this.macnIden = macnIden;
	}

	public Set<RolModActionBO> getRolModActions() {
		return this.rolModActions;
	}

	public void setRolModActions(Set<RolModActionBO> rolModActions) {
		this.rolModActions = rolModActions;
	}

}
