package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProgramDeposit generated by hbm2java
 */
public class ProgramDepositBO  implements  java.io.Serializable {

	private Long pdpstId;
	private ProgramWorksBO programWorks;
	private DepositBO deposit;
	private double pdpstAmount;
	private boolean pdpstRowStatus;
	private Boolean pdpstAplicableYn;

	public ProgramDepositBO() {
	}

	public ProgramDepositBO(ProgramWorksBO programWorks, DepositBO deposit,
			double pdpstAmount, boolean pdpstRowStatus) {
		this.programWorks = programWorks;
		this.deposit = deposit;
		this.pdpstAmount = pdpstAmount;
		this.pdpstRowStatus = pdpstRowStatus;
	}

	public ProgramDepositBO(ProgramWorksBO programWorks, DepositBO deposit,
			double pdpstAmount, boolean pdpstRowStatus, Boolean pdpstAplicableYn) {
		this.programWorks = programWorks;
		this.deposit = deposit;
		this.pdpstAmount = pdpstAmount;
		this.pdpstRowStatus = pdpstRowStatus;
		this.pdpstAplicableYn = pdpstAplicableYn;
	}

	public Long getPdpstId() {
		return this.pdpstId;
	}

	public void setPdpstId(Long pdpstId) {
		this.pdpstId = pdpstId;
	}

	public ProgramWorksBO getProgramWorks() {
		return this.programWorks;
	}

	public void setProgramWorks(ProgramWorksBO programWorks) {
		this.programWorks = programWorks;
	}

	public DepositBO getDeposit() {
		return this.deposit;
	}

	public void setDeposit(DepositBO deposit) {
		this.deposit = deposit;
	}

	public double getPdpstAmount() {
		return this.pdpstAmount;
	}

	public void setPdpstAmount(double pdpstAmount) {
		this.pdpstAmount = pdpstAmount;
	}

	public boolean isPdpstRowStatus() {
		return this.pdpstRowStatus;
	}

	public void setPdpstRowStatus(boolean pdpstRowStatus) {
		this.pdpstRowStatus = pdpstRowStatus;
	}

	public Boolean getPdpstAplicableYn() {
		return this.pdpstAplicableYn;
	}

	public void setPdpstAplicableYn(Boolean pdpstAplicableYn) {
		this.pdpstAplicableYn = pdpstAplicableYn;
	}

}
