package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProgramWorks generated by hbm2java
 */
public class ProgramWorksBO  implements  java.io.Serializable {

	private Long pwrkId;
	private ProgramBO program;
	private TalukBO taluk;
	private SectionBO section;
	private CasteCategoryBO casteCategory;
	private Date pwrkDate;
	private String pwrkUid;
	private Integer pwrkCstctgIdenFlag;
	private String pwrkBeneficiary;
	private Date pwrkRegDate;
	private String pwrkVillage;
	private int pwrkStageIden;
	private String pwrkEstimateNo;
	private Date pwrkEstimateDate;
	private Double pwrkEstimateCost;
	private Date pwrkIntimateDate;
	private String pwrkWoNo;
	private Date pwrkWoIssueDate;
	private String pwrkRrNo;
	private Date pwrkDateOfService;
	private boolean pwrkRowStatus;
	private Integer pwrkSourceIden;
	private Double pwrkRegFee;
	private String pwrkRtno;
	private Date pwrkWorkAwardDate;
	private String pwrkHtLine;
	private String pwrkLtLine;
	private String pwrkTfCapacity;
	private String pwrkTfLoad;
	private Integer pwrkIdenFlag;
	private Set<ProgramStatusBO> programStatuses = new HashSet<ProgramStatusBO>(0);
	private Set<ProgramDepositBO> programDeposits = new HashSet<ProgramDepositBO>(0);

	public ProgramWorksBO() {
	}

	public ProgramWorksBO(ProgramBO program, SectionBO section, Date pwrkDate,
			String pwrkUid, int pwrkStageIden, boolean pwrkRowStatus) {
		this.program = program;
		this.section = section;
		this.pwrkDate = pwrkDate;
		this.pwrkUid = pwrkUid;
		this.pwrkStageIden = pwrkStageIden;
		this.pwrkRowStatus = pwrkRowStatus;
	}

	public ProgramWorksBO(ProgramBO program, TalukBO taluk, SectionBO section,
			CasteCategoryBO casteCategory, Date pwrkDate, String pwrkUid,
			Integer pwrkCstctgIdenFlag, String pwrkBeneficiary,
			Date pwrkRegDate, String pwrkVillage, int pwrkStageIden,
			String pwrkEstimateNo, Date pwrkEstimateDate,
			Double pwrkEstimateCost, Date pwrkIntimateDate, String pwrkWoNo,
			Date pwrkWoIssueDate, String pwrkRrNo, Date pwrkDateOfService,
			boolean pwrkRowStatus, Integer pwrkSourceIden, Double pwrkRegFee,
			String pwrkRtno, Date pwrkWorkAwardDate, String pwrkHtLine,
			String pwrkLtLine, String pwrkTfCapacity, String pwrkTfLoad,
			Integer pwrkIdenFlag, Set<ProgramStatusBO> programStatuses,
			Set<ProgramDepositBO> programDeposits) {
		this.program = program;
		this.taluk = taluk;
		this.section = section;
		this.casteCategory = casteCategory;
		this.pwrkDate = pwrkDate;
		this.pwrkUid = pwrkUid;
		this.pwrkCstctgIdenFlag = pwrkCstctgIdenFlag;
		this.pwrkBeneficiary = pwrkBeneficiary;
		this.pwrkRegDate = pwrkRegDate;
		this.pwrkVillage = pwrkVillage;
		this.pwrkStageIden = pwrkStageIden;
		this.pwrkEstimateNo = pwrkEstimateNo;
		this.pwrkEstimateDate = pwrkEstimateDate;
		this.pwrkEstimateCost = pwrkEstimateCost;
		this.pwrkIntimateDate = pwrkIntimateDate;
		this.pwrkWoNo = pwrkWoNo;
		this.pwrkWoIssueDate = pwrkWoIssueDate;
		this.pwrkRrNo = pwrkRrNo;
		this.pwrkDateOfService = pwrkDateOfService;
		this.pwrkRowStatus = pwrkRowStatus;
		this.pwrkSourceIden = pwrkSourceIden;
		this.pwrkRegFee = pwrkRegFee;
		this.pwrkRtno = pwrkRtno;
		this.pwrkWorkAwardDate = pwrkWorkAwardDate;
		this.pwrkHtLine = pwrkHtLine;
		this.pwrkLtLine = pwrkLtLine;
		this.pwrkTfCapacity = pwrkTfCapacity;
		this.pwrkTfLoad = pwrkTfLoad;
		this.pwrkIdenFlag = pwrkIdenFlag;
		this.programStatuses = programStatuses;
		this.programDeposits = programDeposits;
	}

	public Long getPwrkId() {
		return this.pwrkId;
	}

	public void setPwrkId(Long pwrkId) {
		this.pwrkId = pwrkId;
	}

	public ProgramBO getProgram() {
		return this.program;
	}

	public void setProgram(ProgramBO program) {
		this.program = program;
	}

	public TalukBO getTaluk() {
		return this.taluk;
	}

	public void setTaluk(TalukBO taluk) {
		this.taluk = taluk;
	}

	public SectionBO getSection() {
		return this.section;
	}

	public void setSection(SectionBO section) {
		this.section = section;
	}

	public CasteCategoryBO getCasteCategory() {
		return this.casteCategory;
	}

	public void setCasteCategory(CasteCategoryBO casteCategory) {
		this.casteCategory = casteCategory;
	}

	public Date getPwrkDate() {
		return this.pwrkDate;
	}

	public void setPwrkDate(Date pwrkDate) {
		this.pwrkDate = pwrkDate;
	}

	public String getPwrkUid() {
		return this.pwrkUid;
	}

	public void setPwrkUid(String pwrkUid) {
		this.pwrkUid = pwrkUid;
	}

	public Integer getPwrkCstctgIdenFlag() {
		return this.pwrkCstctgIdenFlag;
	}

	public void setPwrkCstctgIdenFlag(Integer pwrkCstctgIdenFlag) {
		this.pwrkCstctgIdenFlag = pwrkCstctgIdenFlag;
	}

	public String getPwrkBeneficiary() {
		return this.pwrkBeneficiary;
	}

	public void setPwrkBeneficiary(String pwrkBeneficiary) {
		this.pwrkBeneficiary = pwrkBeneficiary;
	}

	public Date getPwrkRegDate() {
		return this.pwrkRegDate;
	}

	public void setPwrkRegDate(Date pwrkRegDate) {
		this.pwrkRegDate = pwrkRegDate;
	}

	public String getPwrkVillage() {
		return this.pwrkVillage;
	}

	public void setPwrkVillage(String pwrkVillage) {
		this.pwrkVillage = pwrkVillage;
	}

	public int getPwrkStageIden() {
		return this.pwrkStageIden;
	}

	public void setPwrkStageIden(int pwrkStageIden) {
		this.pwrkStageIden = pwrkStageIden;
	}

	public String getPwrkEstimateNo() {
		return this.pwrkEstimateNo;
	}

	public void setPwrkEstimateNo(String pwrkEstimateNo) {
		this.pwrkEstimateNo = pwrkEstimateNo;
	}

	public Date getPwrkEstimateDate() {
		return this.pwrkEstimateDate;
	}

	public void setPwrkEstimateDate(Date pwrkEstimateDate) {
		this.pwrkEstimateDate = pwrkEstimateDate;
	}

	public Double getPwrkEstimateCost() {
		return this.pwrkEstimateCost;
	}

	public void setPwrkEstimateCost(Double pwrkEstimateCost) {
		this.pwrkEstimateCost = pwrkEstimateCost;
	}

	public Date getPwrkIntimateDate() {
		return this.pwrkIntimateDate;
	}

	public void setPwrkIntimateDate(Date pwrkIntimateDate) {
		this.pwrkIntimateDate = pwrkIntimateDate;
	}

	public String getPwrkWoNo() {
		return this.pwrkWoNo;
	}

	public void setPwrkWoNo(String pwrkWoNo) {
		this.pwrkWoNo = pwrkWoNo;
	}

	public Date getPwrkWoIssueDate() {
		return this.pwrkWoIssueDate;
	}

	public void setPwrkWoIssueDate(Date pwrkWoIssueDate) {
		this.pwrkWoIssueDate = pwrkWoIssueDate;
	}

	public String getPwrkRrNo() {
		return this.pwrkRrNo;
	}

	public void setPwrkRrNo(String pwrkRrNo) {
		this.pwrkRrNo = pwrkRrNo;
	}

	public Date getPwrkDateOfService() {
		return this.pwrkDateOfService;
	}

	public void setPwrkDateOfService(Date pwrkDateOfService) {
		this.pwrkDateOfService = pwrkDateOfService;
	}

	public boolean isPwrkRowStatus() {
		return this.pwrkRowStatus;
	}

	public void setPwrkRowStatus(boolean pwrkRowStatus) {
		this.pwrkRowStatus = pwrkRowStatus;
	}

	public Integer getPwrkSourceIden() {
		return this.pwrkSourceIden;
	}

	public void setPwrkSourceIden(Integer pwrkSourceIden) {
		this.pwrkSourceIden = pwrkSourceIden;
	}

	public Double getPwrkRegFee() {
		return this.pwrkRegFee;
	}

	public void setPwrkRegFee(Double pwrkRegFee) {
		this.pwrkRegFee = pwrkRegFee;
	}

	public String getPwrkRtno() {
		return this.pwrkRtno;
	}

	public void setPwrkRtno(String pwrkRtno) {
		this.pwrkRtno = pwrkRtno;
	}

	public Date getPwrkWorkAwardDate() {
		return this.pwrkWorkAwardDate;
	}

	public void setPwrkWorkAwardDate(Date pwrkWorkAwardDate) {
		this.pwrkWorkAwardDate = pwrkWorkAwardDate;
	}

	public String getPwrkHtLine() {
		return this.pwrkHtLine;
	}

	public void setPwrkHtLine(String pwrkHtLine) {
		this.pwrkHtLine = pwrkHtLine;
	}

	public String getPwrkLtLine() {
		return this.pwrkLtLine;
	}

	public void setPwrkLtLine(String pwrkLtLine) {
		this.pwrkLtLine = pwrkLtLine;
	}

	public String getPwrkTfCapacity() {
		return this.pwrkTfCapacity;
	}

	public void setPwrkTfCapacity(String pwrkTfCapacity) {
		this.pwrkTfCapacity = pwrkTfCapacity;
	}

	public String getPwrkTfLoad() {
		return this.pwrkTfLoad;
	}

	public void setPwrkTfLoad(String pwrkTfLoad) {
		this.pwrkTfLoad = pwrkTfLoad;
	}

	public Integer getPwrkIdenFlag() {
		return this.pwrkIdenFlag;
	}

	public void setPwrkIdenFlag(Integer pwrkIdenFlag) {
		this.pwrkIdenFlag = pwrkIdenFlag;
	}

	public Set<ProgramStatusBO> getProgramStatuses() {
		return this.programStatuses;
	}

	public void setProgramStatuses(Set<ProgramStatusBO> programStatuses) {
		this.programStatuses = programStatuses;
	}

	public Set<ProgramDepositBO> getProgramDeposits() {
		return this.programDeposits;
	}

	public void setProgramDeposits(Set<ProgramDepositBO> programDeposits) {
		this.programDeposits = programDeposits;
	}

}
