package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class ProgramBO  implements  java.io.Serializable {

	private Integer progrmId;
	private String progrmShortCode;
	private String progrmName;
	private Date progrmStartDate;
	private Date programEndDate;
	private boolean progrmRowStatus;
	private Set<ProgramWorksBO> programWorkses = new HashSet<ProgramWorksBO>(0);

	public ProgramBO() {
	}

	public ProgramBO(String progrmShortCode, String progrmName,
			Date progrmStartDate, boolean progrmRowStatus) {
		this.progrmShortCode = progrmShortCode;
		this.progrmName = progrmName;
		this.progrmStartDate = progrmStartDate;
		this.progrmRowStatus = progrmRowStatus;
	}

	public ProgramBO(String progrmShortCode, String progrmName,
			Date progrmStartDate, Date programEndDate, boolean progrmRowStatus,
			Set<ProgramWorksBO> programWorkses) {
		this.progrmShortCode = progrmShortCode;
		this.progrmName = progrmName;
		this.progrmStartDate = progrmStartDate;
		this.programEndDate = programEndDate;
		this.progrmRowStatus = progrmRowStatus;
		this.programWorkses = programWorkses;
	}

	public Integer getProgrmId() {
		return this.progrmId;
	}

	public void setProgrmId(Integer progrmId) {
		this.progrmId = progrmId;
	}

	public String getProgrmShortCode() {
		return this.progrmShortCode;
	}

	public void setProgrmShortCode(String progrmShortCode) {
		this.progrmShortCode = progrmShortCode;
	}

	public String getProgrmName() {
		return this.progrmName;
	}

	public void setProgrmName(String progrmName) {
		this.progrmName = progrmName;
	}

	public Date getProgrmStartDate() {
		return this.progrmStartDate;
	}

	public void setProgrmStartDate(Date progrmStartDate) {
		this.progrmStartDate = progrmStartDate;
	}

	public Date getProgramEndDate() {
		return this.programEndDate;
	}

	public void setProgramEndDate(Date programEndDate) {
		this.programEndDate = programEndDate;
	}

	public boolean isProgrmRowStatus() {
		return this.progrmRowStatus;
	}

	public void setProgrmRowStatus(boolean progrmRowStatus) {
		this.progrmRowStatus = progrmRowStatus;
	}

	public Set<ProgramWorksBO> getProgramWorkses() {
		return this.programWorkses;
	}

	public void setProgramWorkses(Set<ProgramWorksBO> programWorkses) {
		this.programWorkses = programWorkses;
	}

}
