package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ProgramStatus generated by hbm2java
 */
public class ProgramStatusBO  implements  java.io.Serializable {

	private Integer pstsId;
	private StatusBO status;
	private ProgramWorksBO programWorks;
	private Date pstsDate;
	private Date pstsStsDate;
	private Integer pstsStsFlag;
	private String pstsRemarks;
	private Long pstsRemarksBy;
	private boolean pstsRowStatus;

	public ProgramStatusBO() {
	}

	public ProgramStatusBO(StatusBO status, ProgramWorksBO programWorks,
			boolean pstsRowStatus) {
		this.status = status;
		this.programWorks = programWorks;
		this.pstsRowStatus = pstsRowStatus;
	}

	public ProgramStatusBO(StatusBO status, ProgramWorksBO programWorks,
			Date pstsDate, Date pstsStsDate, Integer pstsStsFlag,
			String pstsRemarks, Long pstsRemarksBy, boolean pstsRowStatus) {
		this.status = status;
		this.programWorks = programWorks;
		this.pstsDate = pstsDate;
		this.pstsStsDate = pstsStsDate;
		this.pstsStsFlag = pstsStsFlag;
		this.pstsRemarks = pstsRemarks;
		this.pstsRemarksBy = pstsRemarksBy;
		this.pstsRowStatus = pstsRowStatus;
	}

	public Integer getPstsId() {
		return this.pstsId;
	}

	public void setPstsId(Integer pstsId) {
		this.pstsId = pstsId;
	}

	public StatusBO getStatus() {
		return this.status;
	}

	public void setStatus(StatusBO status) {
		this.status = status;
	}

	public ProgramWorksBO getProgramWorks() {
		return this.programWorks;
	}

	public void setProgramWorks(ProgramWorksBO programWorks) {
		this.programWorks = programWorks;
	}

	public Date getPstsDate() {
		return this.pstsDate;
	}

	public void setPstsDate(Date pstsDate) {
		this.pstsDate = pstsDate;
	}

	public Date getPstsStsDate() {
		return this.pstsStsDate;
	}

	public void setPstsStsDate(Date pstsStsDate) {
		this.pstsStsDate = pstsStsDate;
	}

	public Integer getPstsStsFlag() {
		return this.pstsStsFlag;
	}

	public void setPstsStsFlag(Integer pstsStsFlag) {
		this.pstsStsFlag = pstsStsFlag;
	}

	public String getPstsRemarks() {
		return this.pstsRemarks;
	}

	public void setPstsRemarks(String pstsRemarks) {
		this.pstsRemarks = pstsRemarks;
	}

	public Long getPstsRemarksBy() {
		return this.pstsRemarksBy;
	}

	public void setPstsRemarksBy(Long pstsRemarksBy) {
		this.pstsRemarksBy = pstsRemarksBy;
	}

	public boolean isPstsRowStatus() {
		return this.pstsRowStatus;
	}

	public void setPstsRowStatus(boolean pstsRowStatus) {
		this.pstsRowStatus = pstsRowStatus;
	}

}
