package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Reports generated by hbm2java
 */
public class ReportsBO  implements  java.io.Serializable {

	private Integer repId;
	private ModuleBO module;
	private String repName;
	private Integer repOrder;
	private String repPath;
	private boolean repRowStatus;
	private Set<ReportMapBO> reportMaps = new HashSet<ReportMapBO>(0);

	public ReportsBO() {
	}

	public ReportsBO(ModuleBO module, String repName, boolean repRowStatus) {
		this.module = module;
		this.repName = repName;
		this.repRowStatus = repRowStatus;
	}

	public ReportsBO(ModuleBO module, String repName, Integer repOrder,
			String repPath, boolean repRowStatus, Set<ReportMapBO> reportMaps) {
		this.module = module;
		this.repName = repName;
		this.repOrder = repOrder;
		this.repPath = repPath;
		this.repRowStatus = repRowStatus;
		this.reportMaps = reportMaps;
	}

	public Integer getRepId() {
		return this.repId;
	}

	public void setRepId(Integer repId) {
		this.repId = repId;
	}

	public ModuleBO getModule() {
		return this.module;
	}

	public void setModule(ModuleBO module) {
		this.module = module;
	}

	public String getRepName() {
		return this.repName;
	}

	public void setRepName(String repName) {
		this.repName = repName;
	}

	public Integer getRepOrder() {
		return this.repOrder;
	}

	public void setRepOrder(Integer repOrder) {
		this.repOrder = repOrder;
	}

	public String getRepPath() {
		return this.repPath;
	}

	public void setRepPath(String repPath) {
		this.repPath = repPath;
	}

	public boolean isRepRowStatus() {
		return this.repRowStatus;
	}

	public void setRepRowStatus(boolean repRowStatus) {
		this.repRowStatus = repRowStatus;
	}

	public Set<ReportMapBO> getReportMaps() {
		return this.reportMaps;
	}

	public void setReportMaps(Set<ReportMapBO> reportMaps) {
		this.reportMaps = reportMaps;
	}

}
