package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * ReportMap generated by hbm2java
 */
public class ReportMapBO  implements  java.io.Serializable {

	private Integer rgmId;
	private ReportsBO reports;
	private ReportGroupBO reportGroup;
	private boolean rgmRowStatus;

	public ReportMapBO() {
	}

	public ReportMapBO(ReportsBO reports, ReportGroupBO reportGroup,
			boolean rgmRowStatus) {
		this.reports = reports;
		this.reportGroup = reportGroup;
		this.rgmRowStatus = rgmRowStatus;
	}

	public Integer getRgmId() {
		return this.rgmId;
	}

	public void setRgmId(Integer rgmId) {
		this.rgmId = rgmId;
	}

	public ReportsBO getReports() {
		return this.reports;
	}

	public void setReports(ReportsBO reports) {
		this.reports = reports;
	}

	public ReportGroupBO getReportGroup() {
		return this.reportGroup;
	}

	public void setReportGroup(ReportGroupBO reportGroup) {
		this.reportGroup = reportGroup;
	}

	public boolean isRgmRowStatus() {
		return this.rgmRowStatus;
	}

	public void setRgmRowStatus(boolean rgmRowStatus) {
		this.rgmRowStatus = rgmRowStatus;
	}

}
