package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ReportGroup generated by hbm2java
 */
public class ReportGroupBO  implements  java.io.Serializable {

	private Integer repgrpId;
	private String repgrpName;
	private boolean repgrpRowStatus;
	private Set<ReportMapBO> reportMaps = new HashSet<ReportMapBO>(0);

	public ReportGroupBO() {
	}

	public ReportGroupBO(String repgrpName, boolean repgrpRowStatus) {
		this.repgrpName = repgrpName;
		this.repgrpRowStatus = repgrpRowStatus;
	}

	public ReportGroupBO(String repgrpName, boolean repgrpRowStatus,
			Set<ReportMapBO> reportMaps) {
		this.repgrpName = repgrpName;
		this.repgrpRowStatus = repgrpRowStatus;
		this.reportMaps = reportMaps;
	}

	public Integer getRepgrpId() {
		return this.repgrpId;
	}

	public void setRepgrpId(Integer repgrpId) {
		this.repgrpId = repgrpId;
	}

	public String getRepgrpName() {
		return this.repgrpName;
	}

	public void setRepgrpName(String repgrpName) {
		this.repgrpName = repgrpName;
	}

	public boolean isRepgrpRowStatus() {
		return this.repgrpRowStatus;
	}

	public void setRepgrpRowStatus(boolean repgrpRowStatus) {
		this.repgrpRowStatus = repgrpRowStatus;
	}

	public Set<ReportMapBO> getReportMaps() {
		return this.reportMaps;
	}

	public void setReportMaps(Set<ReportMapBO> reportMaps) {
		this.reportMaps = reportMaps;
	}

}
