package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * Revenue generated by hbm2java
 */
public class RevenueBO  implements  java.io.Serializable {

	private Long revId;
	private TranHeadBO tranHead;
	private Integer revTotalInstalation;
	private Long revInputEnergy;
	private Long revDcbEnergy;
	private Double revDcbOb;
	private Double revDemand;
	private Double revCollection;
	private Double revDcbCb;
	private String revRemarks;
	private Boolean revRowStatus;

	public RevenueBO() {
	}

	public RevenueBO(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public RevenueBO(TranHeadBO tranHead, Integer revTotalInstalation,
			Long revInputEnergy, Long revDcbEnergy, Double revDcbOb,
			Double revDemand, Double revCollection, Double revDcbCb,
			String revRemarks, Boolean revRowStatus) {
		this.tranHead = tranHead;
		this.revTotalInstalation = revTotalInstalation;
		this.revInputEnergy = revInputEnergy;
		this.revDcbEnergy = revDcbEnergy;
		this.revDcbOb = revDcbOb;
		this.revDemand = revDemand;
		this.revCollection = revCollection;
		this.revDcbCb = revDcbCb;
		this.revRemarks = revRemarks;
		this.revRowStatus = revRowStatus;
	}

	public Long getRevId() {
		return this.revId;
	}

	public void setRevId(Long revId) {
		this.revId = revId;
	}

	public TranHeadBO getTranHead() {
		return this.tranHead;
	}

	public void setTranHead(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public Integer getRevTotalInstalation() {
		return this.revTotalInstalation;
	}

	public void setRevTotalInstalation(Integer revTotalInstalation) {
		this.revTotalInstalation = revTotalInstalation;
	}

	public Long getRevInputEnergy() {
		return this.revInputEnergy;
	}

	public void setRevInputEnergy(Long revInputEnergy) {
		this.revInputEnergy = revInputEnergy;
	}

	public Long getRevDcbEnergy() {
		return this.revDcbEnergy;
	}

	public void setRevDcbEnergy(Long revDcbEnergy) {
		this.revDcbEnergy = revDcbEnergy;
	}

	public Double getRevDcbOb() {
		return this.revDcbOb;
	}

	public void setRevDcbOb(Double revDcbOb) {
		this.revDcbOb = revDcbOb;
	}

	public Double getRevDemand() {
		return this.revDemand;
	}

	public void setRevDemand(Double revDemand) {
		this.revDemand = revDemand;
	}

	public Double getRevCollection() {
		return this.revCollection;
	}

	public void setRevCollection(Double revCollection) {
		this.revCollection = revCollection;
	}

	public Double getRevDcbCb() {
		return this.revDcbCb;
	}

	public void setRevDcbCb(Double revDcbCb) {
		this.revDcbCb = revDcbCb;
	}

	public String getRevRemarks() {
		return this.revRemarks;
	}

	public void setRevRemarks(String revRemarks) {
		this.revRemarks = revRemarks;
	}

	public Boolean getRevRowStatus() {
		return this.revRowStatus;
	}

	public void setRevRowStatus(Boolean revRowStatus) {
		this.revRowStatus = revRowStatus;
	}

}
