package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class RoleBO  implements  java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private boolean roleRowStatus;
	private String roleLn;
	private Set<RolModActionBO> rolModActions = new HashSet<RolModActionBO>(0);
	private Set<UserRolesBO> userRoleses = new HashSet<UserRolesBO>(0);

	public RoleBO() {
	}

	public RoleBO(String roleName, boolean roleRowStatus, String roleLn) {
		this.roleName = roleName;
		this.roleRowStatus = roleRowStatus;
		this.roleLn = roleLn;
	}

	public RoleBO(String roleName, boolean roleRowStatus, String roleLn,
			Set<RolModActionBO> rolModActions, Set<UserRolesBO> userRoleses) {
		this.roleName = roleName;
		this.roleRowStatus = roleRowStatus;
		this.roleLn = roleLn;
		this.rolModActions = rolModActions;
		this.userRoleses = userRoleses;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public boolean isRoleRowStatus() {
		return this.roleRowStatus;
	}

	public void setRoleRowStatus(boolean roleRowStatus) {
		this.roleRowStatus = roleRowStatus;
	}

	public String getRoleLn() {
		return this.roleLn;
	}

	public void setRoleLn(String roleLn) {
		this.roleLn = roleLn;
	}

	public Set<RolModActionBO> getRolModActions() {
		return this.rolModActions;
	}

	public void setRolModActions(Set<RolModActionBO> rolModActions) {
		this.rolModActions = rolModActions;
	}

	public Set<UserRolesBO> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRolesBO> userRoleses) {
		this.userRoleses = userRoleses;
	}

}
