package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * RolModAction generated by hbm2java
 */
public class RolModActionBO  implements  java.io.Serializable {

	private Integer rlmapId;
	private RoleBO role;
	private ModActionBO modAction;
	private boolean rlmapRowStatus;

	public RolModActionBO() {
	}

	public RolModActionBO(RoleBO role, ModActionBO modAction, boolean rlmapRowStatus) {
		this.role = role;
		this.modAction = modAction;
		this.rlmapRowStatus = rlmapRowStatus;
	}

	public Integer getRlmapId() {
		return this.rlmapId;
	}

	public void setRlmapId(Integer rlmapId) {
		this.rlmapId = rlmapId;
	}

	public RoleBO getRole() {
		return this.role;
	}

	public void setRole(RoleBO role) {
		this.role = role;
	}

	public ModActionBO getModAction() {
		return this.modAction;
	}

	public void setModAction(ModActionBO modAction) {
		this.modAction = modAction;
	}

	public boolean isRlmapRowStatus() {
		return this.rlmapRowStatus;
	}

	public void setRlmapRowStatus(boolean rlmapRowStatus) {
		this.rlmapRowStatus = rlmapRowStatus;
	}

}
