package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Section generated by hbm2java
 */
public class SectionBO  implements  java.io.Serializable {

	private Integer sectnId;
	private SubDivisionBO subDivision;
	private String sectnShortCode;
	private String sectnName;
	private Date sectnFromDate;
	private Date sectnToDate;
	private boolean sectnRowStatus;
	private Long sectnCreatedBy;
	private Date sectnCreatedDate;
	private Long sectnLastUpdatedBy;
	private Date sectnLastUpdatedDate;
	private Set<ConstituencyBO> constituencies = new HashSet<ConstituencyBO>(0);
	private Set<ProgramWorksBO> programWorkses = new HashSet<ProgramWorksBO>(0);
	private Set<TranHeadBO> tranHeads = new HashSet<TranHeadBO>(0);

	public SectionBO() {
	}

	public SectionBO(SubDivisionBO subDivision, String sectnShortCode,
			String sectnName, Date sectnFromDate, boolean sectnRowStatus) {
		this.subDivision = subDivision;
		this.sectnShortCode = sectnShortCode;
		this.sectnName = sectnName;
		this.sectnFromDate = sectnFromDate;
		this.sectnRowStatus = sectnRowStatus;
	}

	public SectionBO(SubDivisionBO subDivision, String sectnShortCode,
			String sectnName, Date sectnFromDate, Date sectnToDate,
			boolean sectnRowStatus, Long sectnCreatedBy, Date sectnCreatedDate,
			Long sectnLastUpdatedBy, Date sectnLastUpdatedDate,
			Set<ConstituencyBO> constituencies, Set<ProgramWorksBO> programWorkses,
			Set<TranHeadBO> tranHeads) {
		this.subDivision = subDivision;
		this.sectnShortCode = sectnShortCode;
		this.sectnName = sectnName;
		this.sectnFromDate = sectnFromDate;
		this.sectnToDate = sectnToDate;
		this.sectnRowStatus = sectnRowStatus;
		this.sectnCreatedBy = sectnCreatedBy;
		this.sectnCreatedDate = sectnCreatedDate;
		this.sectnLastUpdatedBy = sectnLastUpdatedBy;
		this.sectnLastUpdatedDate = sectnLastUpdatedDate;
		this.constituencies = constituencies;
		this.programWorkses = programWorkses;
		this.tranHeads = tranHeads;
	}

	public Integer getSectnId() {
		return this.sectnId;
	}

	public void setSectnId(Integer sectnId) {
		this.sectnId = sectnId;
	}

	public SubDivisionBO getSubDivision() {
		return this.subDivision;
	}

	public void setSubDivision(SubDivisionBO subDivision) {
		this.subDivision = subDivision;
	}

	public String getSectnShortCode() {
		return this.sectnShortCode;
	}

	public void setSectnShortCode(String sectnShortCode) {
		this.sectnShortCode = sectnShortCode;
	}

	public String getSectnName() {
		return this.sectnName;
	}

	public void setSectnName(String sectnName) {
		this.sectnName = sectnName;
	}

	public Date getSectnFromDate() {
		return this.sectnFromDate;
	}

	public void setSectnFromDate(Date sectnFromDate) {
		this.sectnFromDate = sectnFromDate;
	}

	public Date getSectnToDate() {
		return this.sectnToDate;
	}

	public void setSectnToDate(Date sectnToDate) {
		this.sectnToDate = sectnToDate;
	}

	public boolean isSectnRowStatus() {
		return this.sectnRowStatus;
	}

	public void setSectnRowStatus(boolean sectnRowStatus) {
		this.sectnRowStatus = sectnRowStatus;
	}

	public Long getSectnCreatedBy() {
		return this.sectnCreatedBy;
	}

	public void setSectnCreatedBy(Long sectnCreatedBy) {
		this.sectnCreatedBy = sectnCreatedBy;
	}

	public Date getSectnCreatedDate() {
		return this.sectnCreatedDate;
	}

	public void setSectnCreatedDate(Date sectnCreatedDate) {
		this.sectnCreatedDate = sectnCreatedDate;
	}

	public Long getSectnLastUpdatedBy() {
		return this.sectnLastUpdatedBy;
	}

	public void setSectnLastUpdatedBy(Long sectnLastUpdatedBy) {
		this.sectnLastUpdatedBy = sectnLastUpdatedBy;
	}

	public Date getSectnLastUpdatedDate() {
		return this.sectnLastUpdatedDate;
	}

	public void setSectnLastUpdatedDate(Date sectnLastUpdatedDate) {
		this.sectnLastUpdatedDate = sectnLastUpdatedDate;
	}

	public Set<ConstituencyBO> getConstituencies() {
		return this.constituencies;
	}

	public void setConstituencies(Set<ConstituencyBO> constituencies) {
		this.constituencies = constituencies;
	}

	public Set<ProgramWorksBO> getProgramWorkses() {
		return this.programWorkses;
	}

	public void setProgramWorkses(Set<ProgramWorksBO> programWorkses) {
		this.programWorkses = programWorkses;
	}

	public Set<TranHeadBO> getTranHeads() {
		return this.tranHeads;
	}

	public void setTranHeads(Set<TranHeadBO> tranHeads) {
		this.tranHeads = tranHeads;
	}

}
