package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class StatusBO  implements  java.io.Serializable {

	private Integer stsId;
	private String stsName;
	private Integer stsFlagIden;
	private boolean stsRowStatus;
	private Integer stsPrefenceOrder;
	private Set<ProgramStatusBO> programStatuses = new HashSet<ProgramStatusBO>(0);

	public StatusBO() {
	}

	public StatusBO(String stsName, boolean stsRowStatus) {
		this.stsName = stsName;
		this.stsRowStatus = stsRowStatus;
	}

	public StatusBO(String stsName, Integer stsFlagIden, boolean stsRowStatus,
			Integer stsPrefenceOrder, Set<ProgramStatusBO> programStatuses) {
		this.stsName = stsName;
		this.stsFlagIden = stsFlagIden;
		this.stsRowStatus = stsRowStatus;
		this.stsPrefenceOrder = stsPrefenceOrder;
		this.programStatuses = programStatuses;
	}

	public Integer getStsId() {
		return this.stsId;
	}

	public void setStsId(Integer stsId) {
		this.stsId = stsId;
	}

	public String getStsName() {
		return this.stsName;
	}

	public void setStsName(String stsName) {
		this.stsName = stsName;
	}

	public Integer getStsFlagIden() {
		return this.stsFlagIden;
	}

	public void setStsFlagIden(Integer stsFlagIden) {
		this.stsFlagIden = stsFlagIden;
	}

	public boolean isStsRowStatus() {
		return this.stsRowStatus;
	}

	public void setStsRowStatus(boolean stsRowStatus) {
		this.stsRowStatus = stsRowStatus;
	}

	public Integer getStsPrefenceOrder() {
		return this.stsPrefenceOrder;
	}

	public void setStsPrefenceOrder(Integer stsPrefenceOrder) {
		this.stsPrefenceOrder = stsPrefenceOrder;
	}

	public Set<ProgramStatusBO> getProgramStatuses() {
		return this.programStatuses;
	}

	public void setProgramStatuses(Set<ProgramStatusBO> programStatuses) {
		this.programStatuses = programStatuses;
	}

}
