package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SubDivision generated by hbm2java
 */
public class SubDivisionBO  implements  java.io.Serializable {

	private Integer subdivId;
	private DivisionBO division;
	private String subdivShortCode;
	private String subdivName;
	private Date subdivFromDate;
	private Date subdivToDate;
	private boolean subdivRowStatus;
	private Long subdivCreatedBy;
	private Date subdivCreatedDate;
	private Long subdivLastUpdatedBy;
	private Date subdivLastUpdatedDate;
	private Set<SectionBO> sections = new HashSet<SectionBO>(0);

	public SubDivisionBO() {
	}

	public SubDivisionBO(DivisionBO division, String subdivShortCode,
			String subdivName, Date subdivFromDate, boolean subdivRowStatus) {
		this.division = division;
		this.subdivShortCode = subdivShortCode;
		this.subdivName = subdivName;
		this.subdivFromDate = subdivFromDate;
		this.subdivRowStatus = subdivRowStatus;
	}

	public SubDivisionBO(DivisionBO division, String subdivShortCode,
			String subdivName, Date subdivFromDate, Date subdivToDate,
			boolean subdivRowStatus, Long subdivCreatedBy,
			Date subdivCreatedDate, Long subdivLastUpdatedBy,
			Date subdivLastUpdatedDate, Set<SectionBO> sections) {
		this.division = division;
		this.subdivShortCode = subdivShortCode;
		this.subdivName = subdivName;
		this.subdivFromDate = subdivFromDate;
		this.subdivToDate = subdivToDate;
		this.subdivRowStatus = subdivRowStatus;
		this.subdivCreatedBy = subdivCreatedBy;
		this.subdivCreatedDate = subdivCreatedDate;
		this.subdivLastUpdatedBy = subdivLastUpdatedBy;
		this.subdivLastUpdatedDate = subdivLastUpdatedDate;
		this.sections = sections;
	}

	public Integer getSubdivId() {
		return this.subdivId;
	}

	public void setSubdivId(Integer subdivId) {
		this.subdivId = subdivId;
	}

	public DivisionBO getDivision() {
		return this.division;
	}

	public void setDivision(DivisionBO division) {
		this.division = division;
	}

	public String getSubdivShortCode() {
		return this.subdivShortCode;
	}

	public void setSubdivShortCode(String subdivShortCode) {
		this.subdivShortCode = subdivShortCode;
	}

	public String getSubdivName() {
		return this.subdivName;
	}

	public void setSubdivName(String subdivName) {
		this.subdivName = subdivName;
	}

	public Date getSubdivFromDate() {
		return this.subdivFromDate;
	}

	public void setSubdivFromDate(Date subdivFromDate) {
		this.subdivFromDate = subdivFromDate;
	}

	public Date getSubdivToDate() {
		return this.subdivToDate;
	}

	public void setSubdivToDate(Date subdivToDate) {
		this.subdivToDate = subdivToDate;
	}

	public boolean isSubdivRowStatus() {
		return this.subdivRowStatus;
	}

	public void setSubdivRowStatus(boolean subdivRowStatus) {
		this.subdivRowStatus = subdivRowStatus;
	}

	public Long getSubdivCreatedBy() {
		return this.subdivCreatedBy;
	}

	public void setSubdivCreatedBy(Long subdivCreatedBy) {
		this.subdivCreatedBy = subdivCreatedBy;
	}

	public Date getSubdivCreatedDate() {
		return this.subdivCreatedDate;
	}

	public void setSubdivCreatedDate(Date subdivCreatedDate) {
		this.subdivCreatedDate = subdivCreatedDate;
	}

	public Long getSubdivLastUpdatedBy() {
		return this.subdivLastUpdatedBy;
	}

	public void setSubdivLastUpdatedBy(Long subdivLastUpdatedBy) {
		this.subdivLastUpdatedBy = subdivLastUpdatedBy;
	}

	public Date getSubdivLastUpdatedDate() {
		return this.subdivLastUpdatedDate;
	}

	public void setSubdivLastUpdatedDate(Date subdivLastUpdatedDate) {
		this.subdivLastUpdatedDate = subdivLastUpdatedDate;
	}

	public Set<SectionBO> getSections() {
		return this.sections;
	}

	public void setSections(Set<SectionBO> sections) {
		this.sections = sections;
	}

}
