package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Taluk generated by hbm2java
 */
public class TalukBO  implements  java.io.Serializable {

	private Integer talukId;
	private String talukShortCode;
	private String talukName;
	private Date talukFromDate;
	private Date talukToDate;
	private boolean talukRowStatus;
	private Long talukCreatedBy;
	private Date talukCreatedDate;
	private Long talukLastUpdatedBy;
	private Date talukLastUpdatedDate;
	private Set<ProgramWorksBO> programWorkses = new HashSet<ProgramWorksBO>(0);

	public TalukBO() {
	}

	public TalukBO(String talukShortCode, String talukName, Date talukFromDate,
			boolean talukRowStatus) {
		this.talukShortCode = talukShortCode;
		this.talukName = talukName;
		this.talukFromDate = talukFromDate;
		this.talukRowStatus = talukRowStatus;
	}

	public TalukBO(String talukShortCode, String talukName, Date talukFromDate,
			Date talukToDate, boolean talukRowStatus, Long talukCreatedBy,
			Date talukCreatedDate, Long talukLastUpdatedBy,
			Date talukLastUpdatedDate, Set<ProgramWorksBO> programWorkses) {
		this.talukShortCode = talukShortCode;
		this.talukName = talukName;
		this.talukFromDate = talukFromDate;
		this.talukToDate = talukToDate;
		this.talukRowStatus = talukRowStatus;
		this.talukCreatedBy = talukCreatedBy;
		this.talukCreatedDate = talukCreatedDate;
		this.talukLastUpdatedBy = talukLastUpdatedBy;
		this.talukLastUpdatedDate = talukLastUpdatedDate;
		this.programWorkses = programWorkses;
	}

	public Integer getTalukId() {
		return this.talukId;
	}

	public void setTalukId(Integer talukId) {
		this.talukId = talukId;
	}

	public String getTalukShortCode() {
		return this.talukShortCode;
	}

	public void setTalukShortCode(String talukShortCode) {
		this.talukShortCode = talukShortCode;
	}

	public String getTalukName() {
		return this.talukName;
	}

	public void setTalukName(String talukName) {
		this.talukName = talukName;
	}

	public Date getTalukFromDate() {
		return this.talukFromDate;
	}

	public void setTalukFromDate(Date talukFromDate) {
		this.talukFromDate = talukFromDate;
	}

	public Date getTalukToDate() {
		return this.talukToDate;
	}

	public void setTalukToDate(Date talukToDate) {
		this.talukToDate = talukToDate;
	}

	public boolean isTalukRowStatus() {
		return this.talukRowStatus;
	}

	public void setTalukRowStatus(boolean talukRowStatus) {
		this.talukRowStatus = talukRowStatus;
	}

	public Long getTalukCreatedBy() {
		return this.talukCreatedBy;
	}

	public void setTalukCreatedBy(Long talukCreatedBy) {
		this.talukCreatedBy = talukCreatedBy;
	}

	public Date getTalukCreatedDate() {
		return this.talukCreatedDate;
	}

	public void setTalukCreatedDate(Date talukCreatedDate) {
		this.talukCreatedDate = talukCreatedDate;
	}

	public Long getTalukLastUpdatedBy() {
		return this.talukLastUpdatedBy;
	}

	public void setTalukLastUpdatedBy(Long talukLastUpdatedBy) {
		this.talukLastUpdatedBy = talukLastUpdatedBy;
	}

	public Date getTalukLastUpdatedDate() {
		return this.talukLastUpdatedDate;
	}

	public void setTalukLastUpdatedDate(Date talukLastUpdatedDate) {
		this.talukLastUpdatedDate = talukLastUpdatedDate;
	}

	public Set<ProgramWorksBO> getProgramWorkses() {
		return this.programWorkses;
	}

	public void setProgramWorkses(Set<ProgramWorksBO> programWorkses) {
		this.programWorkses = programWorkses;
	}

}
