package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * TariffDca generated by hbm2java
 */
public class TariffDcaBO  implements  java.io.Serializable {

	private Long tdcaId;
	private TranHeadBO tranHead;
	private TariffBO tariff;
	private Double tdcaDemand;
	private Double tdcaConsumption;
	private Double tdcaArreras;
	private boolean tdcaRowStatus;

	public TariffDcaBO() {
	}

	public TariffDcaBO(TranHeadBO tranHead, TariffBO tariff, boolean tdcaRowStatus) {
		this.tranHead = tranHead;
		this.tariff = tariff;
		this.tdcaRowStatus = tdcaRowStatus;
	}

	public TariffDcaBO(TranHeadBO tranHead, TariffBO tariff, Double tdcaDemand,
			Double tdcaConsumption, Double tdcaArreras, boolean tdcaRowStatus) {
		this.tranHead = tranHead;
		this.tariff = tariff;
		this.tdcaDemand = tdcaDemand;
		this.tdcaConsumption = tdcaConsumption;
		this.tdcaArreras = tdcaArreras;
		this.tdcaRowStatus = tdcaRowStatus;
	}

	public Long getTdcaId() {
		return this.tdcaId;
	}

	public void setTdcaId(Long tdcaId) {
		this.tdcaId = tdcaId;
	}

	public TranHeadBO getTranHead() {
		return this.tranHead;
	}

	public void setTranHead(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public TariffBO getTariff() {
		return this.tariff;
	}

	public void setTariff(TariffBO tariff) {
		this.tariff = tariff;
	}

	public Double getTdcaDemand() {
		return this.tdcaDemand;
	}

	public void setTdcaDemand(Double tdcaDemand) {
		this.tdcaDemand = tdcaDemand;
	}

	public Double getTdcaConsumption() {
		return this.tdcaConsumption;
	}

	public void setTdcaConsumption(Double tdcaConsumption) {
		this.tdcaConsumption = tdcaConsumption;
	}

	public Double getTdcaArreras() {
		return this.tdcaArreras;
	}

	public void setTdcaArreras(Double tdcaArreras) {
		this.tdcaArreras = tdcaArreras;
	}

	public boolean isTdcaRowStatus() {
		return this.tdcaRowStatus;
	}

	public void setTdcaRowStatus(boolean tdcaRowStatus) {
		this.tdcaRowStatus = tdcaRowStatus;
	}

}
