package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tariff generated by hbm2java
 */
public class TariffBO  implements  java.io.Serializable {

	private Integer trfId;
	private String trfName;
	private boolean trfRowStatus;
	private Set<TariffDcaBO> tariffDcas = new HashSet<TariffDcaBO>(0);

	public TariffBO() {
	}

	public TariffBO(String trfName, boolean trfRowStatus) {
		this.trfName = trfName;
		this.trfRowStatus = trfRowStatus;
	}

	public TariffBO(String trfName, boolean trfRowStatus,
			Set<TariffDcaBO> tariffDcas) {
		this.trfName = trfName;
		this.trfRowStatus = trfRowStatus;
		this.tariffDcas = tariffDcas;
	}

	public Integer getTrfId() {
		return this.trfId;
	}

	public void setTrfId(Integer trfId) {
		this.trfId = trfId;
	}

	public String getTrfName() {
		return this.trfName;
	}

	public void setTrfName(String trfName) {
		this.trfName = trfName;
	}

	public boolean isTrfRowStatus() {
		return this.trfRowStatus;
	}

	public void setTrfRowStatus(boolean trfRowStatus) {
		this.trfRowStatus = trfRowStatus;
	}

	public Set<TariffDcaBO> getTariffDcas() {
		return this.tariffDcas;
	}

	public void setTariffDcas(Set<TariffDcaBO> tariffDcas) {
		this.tariffDcas = tariffDcas;
	}

}
