package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * TransformerBO generated by hbm2java
 */
public class TransformerBO implements  java.io.Serializable {

	private Long tfId;
	private CapacityBO capacity;
	private TranHeadBO tranHead;
	private int tfUrFlag;
	private Integer tfAdd;
	private Integer tfFailed;
	private Integer tfReplaced;
	private Integer tfMaintenance;
	private boolean tfRowStatus;

	public TransformerBO() {
	}

	public TransformerBO(CapacityBO capacity, TranHeadBO tranHead, int tfUrFlag,
			boolean tfRowStatus) {
		this.capacity = capacity;
		this.tranHead = tranHead;
		this.tfUrFlag = tfUrFlag;
		this.tfRowStatus = tfRowStatus;
	}

	public TransformerBO(CapacityBO capacity, TranHeadBO tranHead, int tfUrFlag,
			Integer tfAdd, Integer tfFailed, Integer tfReplaced,
			Integer tfMaintenance, boolean tfRowStatus) {
		this.capacity = capacity;
		this.tranHead = tranHead;
		this.tfUrFlag = tfUrFlag;
		this.tfAdd = tfAdd;
		this.tfFailed = tfFailed;
		this.tfReplaced = tfReplaced;
		this.tfMaintenance = tfMaintenance;
		this.tfRowStatus = tfRowStatus;
	}

	public Long getTfId() {
		return this.tfId;
	}

	public void setTfId(Long tfId) {
		this.tfId = tfId;
	}

	public CapacityBO getCapacity() {
		return this.capacity;
	}

	public void setCapacity(CapacityBO capacity) {
		this.capacity = capacity;
	}

	public TranHeadBO getTranHead() {
		return this.tranHead;
	}

	public void setTranHead(TranHeadBO tranHead) {
		this.tranHead = tranHead;
	}

	public int getTfUrFlag() {
		return this.tfUrFlag;
	}

	public void setTfUrFlag(int tfUrFlag) {
		this.tfUrFlag = tfUrFlag;
	}

	public Integer getTfAdd() {
		return this.tfAdd;
	}

	public void setTfAdd(Integer tfAdd) {
		this.tfAdd = tfAdd;
	}

	public Integer getTfFailed() {
		return this.tfFailed;
	}

	public void setTfFailed(Integer tfFailed) {
		this.tfFailed = tfFailed;
	}

	public Integer getTfReplaced() {
		return this.tfReplaced;
	}

	public void setTfReplaced(Integer tfReplaced) {
		this.tfReplaced = tfReplaced;
	}

	public Integer getTfMaintenance() {
		return this.tfMaintenance;
	}

	public void setTfMaintenance(Integer tfMaintenance) {
		this.tfMaintenance = tfMaintenance;
	}

	public boolean isTfRowStatus() {
		return this.tfRowStatus;
	}

	public void setTfRowStatus(boolean tfRowStatus) {
		this.tfRowStatus = tfRowStatus;
	}

}
