package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TranHead generated by hbm2java
 */
public class TranHeadBO  implements  java.io.Serializable {

	private Long thId;
	private SectionBO section;
	private Date thDate;
	private int thMonth;
	private String thYear;
	private byte thRowStatus;
	private int thIdenFlag;
	private Long thTrnsfrmrFldOpbal;
	private Long thTrnsfrmrFldCbbal;
	private Long thMnrInstalled;
	private Long thMnrReplaced;
	private String thMnrReason;
	private Integer thCrpdetInspection;
	private String thCrpdetRemarks;
	private Integer thMetrdWsupply;
	private Integer thUnmetrdWsupply;
	private Set<TransformerBO> transformers = new HashSet<TransformerBO>(0);
	private Set<FeederLineBO> feederLines = new HashSet<FeederLineBO>(0);
	private Set<DoorlockBO> doorlocks = new HashSet<DoorlockBO>(0);
	private Set<TariffDcaBO> tariffDcas = new HashSet<TariffDcaBO>(0);
	private Set<DisconnectionBO> disconnections = new HashSet<DisconnectionBO>(0);
	private Set<InstalationBO> instalations = new HashSet<InstalationBO>(0);
	private Set<MnrDetailBO> mnrDetails = new HashSet<MnrDetailBO>(0);
	private Set<RevenueBO> revenues = new HashSet<RevenueBO>(0);
	private Set<DiscrepancyDetailBO> discrepancyDetails = new HashSet<DiscrepancyDetailBO>(
			0);

	public TranHeadBO() {
	}

	public TranHeadBO(SectionBO section, Date thDate, int thMonth, String thYear,
			byte thRowStatus, int thIdenFlag) {
		this.section = section;
		this.thDate = thDate;
		this.thMonth = thMonth;
		this.thYear = thYear;
		this.thRowStatus = thRowStatus;
		this.thIdenFlag = thIdenFlag;
	}

	public TranHeadBO(SectionBO section, Date thDate, int thMonth, String thYear,
			byte thRowStatus, int thIdenFlag, Long thTrnsfrmrFldOpbal,
			Long thTrnsfrmrFldCbbal, Long thMnrInstalled, Long thMnrReplaced,
			String thMnrReason, Integer thCrpdetInspection,
			String thCrpdetRemarks, Integer thMetrdWsupply,
			Integer thUnmetrdWsupply, Set<TransformerBO> transformers,
			Set<FeederLineBO> feederLines, Set<DoorlockBO> doorlocks,
			Set<TariffDcaBO> tariffDcas, Set<DisconnectionBO> disconnections,
			Set<InstalationBO> instalations, Set<MnrDetailBO> mnrDetails,
			Set<RevenueBO> revenues, Set<DiscrepancyDetailBO> discrepancyDetails) {
		this.section = section;
		this.thDate = thDate;
		this.thMonth = thMonth;
		this.thYear = thYear;
		this.thRowStatus = thRowStatus;
		this.thIdenFlag = thIdenFlag;
		this.thTrnsfrmrFldOpbal = thTrnsfrmrFldOpbal;
		this.thTrnsfrmrFldCbbal = thTrnsfrmrFldCbbal;
		this.thMnrInstalled = thMnrInstalled;
		this.thMnrReplaced = thMnrReplaced;
		this.thMnrReason = thMnrReason;
		this.thCrpdetInspection = thCrpdetInspection;
		this.thCrpdetRemarks = thCrpdetRemarks;
		this.thMetrdWsupply = thMetrdWsupply;
		this.thUnmetrdWsupply = thUnmetrdWsupply;
		this.transformers = transformers;
		this.feederLines = feederLines;
		this.doorlocks = doorlocks;
		this.tariffDcas = tariffDcas;
		this.disconnections = disconnections;
		this.instalations = instalations;
		this.mnrDetails = mnrDetails;
		this.revenues = revenues;
		this.discrepancyDetails = discrepancyDetails;
	}

	public Long getThId() {
		return this.thId;
	}

	public void setThId(Long thId) {
		this.thId = thId;
	}

	public SectionBO getSection() {
		return this.section;
	}

	public void setSection(SectionBO section) {
		this.section = section;
	}

	public Date getThDate() {
		return this.thDate;
	}

	public void setThDate(Date thDate) {
		this.thDate = thDate;
	}

	public int getThMonth() {
		return this.thMonth;
	}

	public void setThMonth(int thMonth) {
		this.thMonth = thMonth;
	}

	public String getThYear() {
		return this.thYear;
	}

	public void setThYear(String thYear) {
		this.thYear = thYear;
	}

	public byte getThRowStatus() {
		return this.thRowStatus;
	}

	public void setThRowStatus(byte thRowStatus) {
		this.thRowStatus = thRowStatus;
	}

	public int getThIdenFlag() {
		return this.thIdenFlag;
	}

	public void setThIdenFlag(int thIdenFlag) {
		this.thIdenFlag = thIdenFlag;
	}

	public Long getThTrnsfrmrFldOpbal() {
		return this.thTrnsfrmrFldOpbal;
	}

	public void setThTrnsfrmrFldOpbal(Long thTrnsfrmrFldOpbal) {
		this.thTrnsfrmrFldOpbal = thTrnsfrmrFldOpbal;
	}

	public Long getThTrnsfrmrFldCbbal() {
		return this.thTrnsfrmrFldCbbal;
	}

	public void setThTrnsfrmrFldCbbal(Long thTrnsfrmrFldCbbal) {
		this.thTrnsfrmrFldCbbal = thTrnsfrmrFldCbbal;
	}

	public Long getThMnrInstalled() {
		return this.thMnrInstalled;
	}

	public void setThMnrInstalled(Long thMnrInstalled) {
		this.thMnrInstalled = thMnrInstalled;
	}

	public Long getThMnrReplaced() {
		return this.thMnrReplaced;
	}

	public void setThMnrReplaced(Long thMnrReplaced) {
		this.thMnrReplaced = thMnrReplaced;
	}

	public String getThMnrReason() {
		return this.thMnrReason;
	}

	public void setThMnrReason(String thMnrReason) {
		this.thMnrReason = thMnrReason;
	}

	public Integer getThCrpdetInspection() {
		return this.thCrpdetInspection;
	}

	public void setThCrpdetInspection(Integer thCrpdetInspection) {
		this.thCrpdetInspection = thCrpdetInspection;
	}

	public String getThCrpdetRemarks() {
		return this.thCrpdetRemarks;
	}

	public void setThCrpdetRemarks(String thCrpdetRemarks) {
		this.thCrpdetRemarks = thCrpdetRemarks;
	}

	public Integer getThMetrdWsupply() {
		return this.thMetrdWsupply;
	}

	public void setThMetrdWsupply(Integer thMetrdWsupply) {
		this.thMetrdWsupply = thMetrdWsupply;
	}

	public Integer getThUnmetrdWsupply() {
		return this.thUnmetrdWsupply;
	}

	public void setThUnmetrdWsupply(Integer thUnmetrdWsupply) {
		this.thUnmetrdWsupply = thUnmetrdWsupply;
	}

	public Set<TransformerBO> getTransformers() {
		return this.transformers;
	}

	public void setTransformers(Set<TransformerBO> transformers) {
		this.transformers = transformers;
	}

	public Set<FeederLineBO> getFeederLines() {
		return this.feederLines;
	}

	public void setFeederLines(Set<FeederLineBO> feederLines) {
		this.feederLines = feederLines;
	}

	public Set<DoorlockBO> getDoorlocks() {
		return this.doorlocks;
	}

	public void setDoorlocks(Set<DoorlockBO> doorlocks) {
		this.doorlocks = doorlocks;
	}

	public Set<TariffDcaBO> getTariffDcas() {
		return this.tariffDcas;
	}

	public void setTariffDcas(Set<TariffDcaBO> tariffDcas) {
		this.tariffDcas = tariffDcas;
	}

	public Set<DisconnectionBO> getDisconnections() {
		return this.disconnections;
	}

	public void setDisconnections(Set<DisconnectionBO> disconnections) {
		this.disconnections = disconnections;
	}

	public Set<InstalationBO> getInstalations() {
		return this.instalations;
	}

	public void setInstalations(Set<InstalationBO> instalations) {
		this.instalations = instalations;
	}

	public Set<MnrDetailBO> getMnrDetails() {
		return this.mnrDetails;
	}

	public void setMnrDetails(Set<MnrDetailBO> mnrDetails) {
		this.mnrDetails = mnrDetails;
	}

	public Set<RevenueBO> getRevenues() {
		return this.revenues;
	}

	public void setRevenues(Set<RevenueBO> revenues) {
		this.revenues = revenues;
	}

	public Set<DiscrepancyDetailBO> getDiscrepancyDetails() {
		return this.discrepancyDetails;
	}

	public void setDiscrepancyDetails(Set<DiscrepancyDetailBO> discrepancyDetails) {
		this.discrepancyDetails = discrepancyDetails;
	}

}
