package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsersBO generated by hbm2java
 */
public class UsersBO implements  java.io.Serializable {

	private Long userId;
	private EmployeeBO employee;
	private String userName;
	private String userPassword;
	private int userStatsFlag;
	private Date userLastAccessedDate;
	private Date userPwdChangedDate;
	private Date userPwdExpDate;
	private String userForgotUrl;
	private Date userForgotExpryDate;
	private Boolean userForgotUrlStats;
	private Long userCreatedBy;
	private Date userCreatedDate;
	private Long userLastUpdatedBy;
	private Date userLastUpdatedDate;
	private Set<UserRolesBO> userRoleses = new HashSet<UserRolesBO>(0);
	private Set<UserMapBO> userMaps = new HashSet<UserMapBO>(0);

	public UsersBO() {
	}

	public UsersBO(String userName, String userPassword, int userStatsFlag) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userStatsFlag = userStatsFlag;
	}

	public UsersBO(EmployeeBO employee, String userName, String userPassword,
			int userStatsFlag, Date userLastAccessedDate,
			Date userPwdChangedDate, Date userPwdExpDate, String userForgotUrl,
			Date userForgotExpryDate, Boolean userForgotUrlStats,
			Long userCreatedBy, Date userCreatedDate, Long userLastUpdatedBy,
			Date userLastUpdatedDate, Set<UserRolesBO> userRoleses,
			Set<UserMapBO> userMaps) {
		this.employee = employee;
		this.userName = userName;
		this.userPassword = userPassword;
		this.userStatsFlag = userStatsFlag;
		this.userLastAccessedDate = userLastAccessedDate;
		this.userPwdChangedDate = userPwdChangedDate;
		this.userPwdExpDate = userPwdExpDate;
		this.userForgotUrl = userForgotUrl;
		this.userForgotExpryDate = userForgotExpryDate;
		this.userForgotUrlStats = userForgotUrlStats;
		this.userCreatedBy = userCreatedBy;
		this.userCreatedDate = userCreatedDate;
		this.userLastUpdatedBy = userLastUpdatedBy;
		this.userLastUpdatedDate = userLastUpdatedDate;
		this.userRoleses = userRoleses;
		this.userMaps = userMaps;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public EmployeeBO getEmployee() {
		return this.employee;
	}

	public void setEmployee(EmployeeBO employee) {
		this.employee = employee;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public int getUserStatsFlag() {
		return this.userStatsFlag;
	}

	public void setUserStatsFlag(int userStatsFlag) {
		this.userStatsFlag = userStatsFlag;
	}

	public Date getUserLastAccessedDate() {
		return this.userLastAccessedDate;
	}

	public void setUserLastAccessedDate(Date userLastAccessedDate) {
		this.userLastAccessedDate = userLastAccessedDate;
	}

	public Date getUserPwdChangedDate() {
		return this.userPwdChangedDate;
	}

	public void setUserPwdChangedDate(Date userPwdChangedDate) {
		this.userPwdChangedDate = userPwdChangedDate;
	}

	public Date getUserPwdExpDate() {
		return this.userPwdExpDate;
	}

	public void setUserPwdExpDate(Date userPwdExpDate) {
		this.userPwdExpDate = userPwdExpDate;
	}

	public String getUserForgotUrl() {
		return this.userForgotUrl;
	}

	public void setUserForgotUrl(String userForgotUrl) {
		this.userForgotUrl = userForgotUrl;
	}

	public Date getUserForgotExpryDate() {
		return this.userForgotExpryDate;
	}

	public void setUserForgotExpryDate(Date userForgotExpryDate) {
		this.userForgotExpryDate = userForgotExpryDate;
	}

	public Boolean getUserForgotUrlStats() {
		return this.userForgotUrlStats;
	}

	public void setUserForgotUrlStats(Boolean userForgotUrlStats) {
		this.userForgotUrlStats = userForgotUrlStats;
	}

	public Long getUserCreatedBy() {
		return this.userCreatedBy;
	}

	public void setUserCreatedBy(Long userCreatedBy) {
		this.userCreatedBy = userCreatedBy;
	}

	public Date getUserCreatedDate() {
		return this.userCreatedDate;
	}

	public void setUserCreatedDate(Date userCreatedDate) {
		this.userCreatedDate = userCreatedDate;
	}

	public Long getUserLastUpdatedBy() {
		return this.userLastUpdatedBy;
	}

	public void setUserLastUpdatedBy(Long userLastUpdatedBy) {
		this.userLastUpdatedBy = userLastUpdatedBy;
	}

	public Date getUserLastUpdatedDate() {
		return this.userLastUpdatedDate;
	}

	public void setUserLastUpdatedDate(Date userLastUpdatedDate) {
		this.userLastUpdatedDate = userLastUpdatedDate;
	}

	public Set<UserRolesBO> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRolesBO> userRoleses) {
		this.userRoleses = userRoleses;
	}

	public Set<UserMapBO> getUserMaps() {
		return this.userMaps;
	}

	public void setUserMaps(Set<UserMapBO> userMaps) {
		this.userMaps = userMaps;
	}

}
