package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserMapBO generated by hbm2java
 */
public class UserMapBO implements  java.io.Serializable {

	private Long umapId;
	private UsersBO users;
	private int umapIdenFlag;
	private int umapFkId;
	private Integer umapPreference;
	private Date umapFromDate;
	private Date umapToDate;
	private boolean umapRowStatus;

	public UserMapBO() {
	}

	public UserMapBO(UsersBO users, int umapIdenFlag, int umapFkId,
			Date umapFromDate, boolean umapRowStatus) {
		this.users = users;
		this.umapIdenFlag = umapIdenFlag;
		this.umapFkId = umapFkId;
		this.umapFromDate = umapFromDate;
		this.umapRowStatus = umapRowStatus;
	}

	public UserMapBO(UsersBO users, int umapIdenFlag, int umapFkId,
			Integer umapPreference, Date umapFromDate, Date umapToDate,
			boolean umapRowStatus) {
		this.users = users;
		this.umapIdenFlag = umapIdenFlag;
		this.umapFkId = umapFkId;
		this.umapPreference = umapPreference;
		this.umapFromDate = umapFromDate;
		this.umapToDate = umapToDate;
		this.umapRowStatus = umapRowStatus;
	}

	public Long getUmapId() {
		return this.umapId;
	}

	public void setUmapId(Long umapId) {
		this.umapId = umapId;
	}

	public UsersBO getUsers() {
		return this.users;
	}

	public void setUsers(UsersBO users) {
		this.users = users;
	}

	public int getUmapIdenFlag() {
		return this.umapIdenFlag;
	}

	public void setUmapIdenFlag(int umapIdenFlag) {
		this.umapIdenFlag = umapIdenFlag;
	}

	public int getUmapFkId() {
		return this.umapFkId;
	}

	public void setUmapFkId(int umapFkId) {
		this.umapFkId = umapFkId;
	}

	public Integer getUmapPreference() {
		return this.umapPreference;
	}

	public void setUmapPreference(Integer umapPreference) {
		this.umapPreference = umapPreference;
	}

	public Date getUmapFromDate() {
		return this.umapFromDate;
	}

	public void setUmapFromDate(Date umapFromDate) {
		this.umapFromDate = umapFromDate;
	}

	public Date getUmapToDate() {
		return this.umapToDate;
	}

	public void setUmapToDate(Date umapToDate) {
		this.umapToDate = umapToDate;
	}

	public boolean isUmapRowStatus() {
		return this.umapRowStatus;
	}

	public void setUmapRowStatus(boolean umapRowStatus) {
		this.umapRowStatus = umapRowStatus;
	}

}
