package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserRolesBO generated by hbm2java
 */
public class UserRolesBO implements  java.io.Serializable {

	private Long usrolId;
	private UsersBO users;
	private RoleBO role;
	private boolean usrolRowStatus;

	public UserRolesBO() {
	}

	public UserRolesBO(UsersBO users, RoleBO role, boolean usrolRowStatus) {
		this.users = users;
		this.role = role;
		this.usrolRowStatus = usrolRowStatus;
	}

	public Long getUsrolId() {
		return this.usrolId;
	}

	public void setUsrolId(Long usrolId) {
		this.usrolId = usrolId;
	}

	public UsersBO getUsers() {
		return this.users;
	}

	public void setUsers(UsersBO users) {
		this.users = users;
	}

	public RoleBO getRole() {
		return this.role;
	}

	public void setRole(RoleBO role) {
		this.role = role;
	}

	public boolean isUsrolRowStatus() {
		return this.usrolRowStatus;
	}

	public void setUsrolRowStatus(boolean usrolRowStatus) {
		this.usrolRowStatus = usrolRowStatus;
	}

}
