package com.ample.mis.hibernate.bo;
// Generated Dec 13, 2012 11:32:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ZoneBO generated by hbm2java
 */
public class ZoneBO  implements  java.io.Serializable {

	private Integer zoneId;
	private String zoneShortCode;
	private String zoneName;
	private Date zoneFromDate;
	private Date zoneToDate;
	private boolean zoneRowStatus;
	private Long zoneCreatedBy;
	private Date zoneCreatedDate;
	private Long zoneLastUpdatedBy;
	private Date zoneLastUpdatedDate;
	private Set<CircleBO> circles = new HashSet<CircleBO>(0);

	public ZoneBO() {
	}

	public ZoneBO(String zoneShortCode, String zoneName, Date zoneFromDate,
			boolean zoneRowStatus) {
		this.zoneShortCode = zoneShortCode;
		this.zoneName = zoneName;
		this.zoneFromDate = zoneFromDate;
		this.zoneRowStatus = zoneRowStatus;
	}

	public ZoneBO(String zoneShortCode, String zoneName, Date zoneFromDate,
			Date zoneToDate, boolean zoneRowStatus, Long zoneCreatedBy,
			Date zoneCreatedDate, Long zoneLastUpdatedBy,
			Date zoneLastUpdatedDate, Set<CircleBO> circles) {
		this.zoneShortCode = zoneShortCode;
		this.zoneName = zoneName;
		this.zoneFromDate = zoneFromDate;
		this.zoneToDate = zoneToDate;
		this.zoneRowStatus = zoneRowStatus;
		this.zoneCreatedBy = zoneCreatedBy;
		this.zoneCreatedDate = zoneCreatedDate;
		this.zoneLastUpdatedBy = zoneLastUpdatedBy;
		this.zoneLastUpdatedDate = zoneLastUpdatedDate;
		this.circles = circles;
	}

	public Integer getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(Integer zoneId) {
		this.zoneId = zoneId;
	}

	public String getZoneShortCode() {
		return this.zoneShortCode;
	}

	public void setZoneShortCode(String zoneShortCode) {
		this.zoneShortCode = zoneShortCode;
	}

	public String getZoneName() {
		return this.zoneName;
	}

	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}

	public Date getZoneFromDate() {
		return this.zoneFromDate;
	}

	public void setZoneFromDate(Date zoneFromDate) {
		this.zoneFromDate = zoneFromDate;
	}

	public Date getZoneToDate() {
		return this.zoneToDate;
	}

	public void setZoneToDate(Date zoneToDate) {
		this.zoneToDate = zoneToDate;
	}

	public boolean isZoneRowStatus() {
		return this.zoneRowStatus;
	}

	public void setZoneRowStatus(boolean zoneRowStatus) {
		this.zoneRowStatus = zoneRowStatus;
	}

	public Long getZoneCreatedBy() {
		return this.zoneCreatedBy;
	}

	public void setZoneCreatedBy(Long zoneCreatedBy) {
		this.zoneCreatedBy = zoneCreatedBy;
	}

	public Date getZoneCreatedDate() {
		return this.zoneCreatedDate;
	}

	public void setZoneCreatedDate(Date zoneCreatedDate) {
		this.zoneCreatedDate = zoneCreatedDate;
	}

	public Long getZoneLastUpdatedBy() {
		return this.zoneLastUpdatedBy;
	}

	public void setZoneLastUpdatedBy(Long zoneLastUpdatedBy) {
		this.zoneLastUpdatedBy = zoneLastUpdatedBy;
	}

	public Date getZoneLastUpdatedDate() {
		return this.zoneLastUpdatedDate;
	}

	public void setZoneLastUpdatedDate(Date zoneLastUpdatedDate) {
		this.zoneLastUpdatedDate = zoneLastUpdatedDate;
	}

	public Set<CircleBO> getCircles() {
		return this.circles;
	}

	public void setCircles(Set<CircleBO> circles) {
		this.circles = circles;
	}

}
